### ISSUE TITLE
Python 3.10 is not available for AWS Lambda, please use one of ['3.6', '3.7', '3.8', '3.9'], or use a container runtime

### ISSUE THREAD

**Issue by sakyb7** [lithops-cloud/lithops#1105]
there is problem with python 3.10

```bash
(env) blackbox@blackbox-desktop:~/tools/ShadowClone$ lithops test
2023-05-24 16:02:45,580 [INFO] config.py:134 -- Lithops v2.9.0
2023-05-24 16:02:45,813 [INFO] aws_s3.py:67 -- S3 client created - Region: us-east-1
2023-05-24 16:02:46,959 [INFO] aws_lambda.py:94 -- AWS Lambda client created - Region: us-east-1
Traceback (most recent call last):
  File "/home/blackbox/tools/ShadowClone/env/bin/lithops", line 8, in <module>
    sys.exit(lithops_cli())
  File "/home/blackbox/tools/ShadowClone/env/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/blackbox/tools/ShadowClone/env/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/blackbox/tools/ShadowClone/env/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/blackbox/tools/ShadowClone/env/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/blackbox/tools/ShadowClone/env/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/blackbox/tools/ShadowClone/env/lib/python3.10/site-packages/lithops/scripts/cli.py", line 174, in test_function
    fexec = lithops.FunctionExecutor(config=config, backend=backend, storage=storage)
  File "/home/blackbox/tools/ShadowClone/env/lib/python3.10/site-packages/lithops/executors.py", line 156, in __init__
    self.invoker = create_invoker(
  File "/home/blackbox/tools/ShadowClone/env/lib/python3.10/site-packages/lithops/invokers.py", line 53, in create_invoker
    return FaaSInvoker(
  File "/home/blackbox/tools/ShadowClone/env/lib/python3.10/site-packages/lithops/invokers.py", line 279, in __init__
    super().__init__(config, executor_id, internal_storage, compute_handler, job_monitor)
  File "/home/blackbox/tools/ShadowClone/env/lib/python3.10/site-packages/lithops/invokers.py", line 88, in __init__
    self.runtime_info = self.compute_handler.get_runtime_info()
  File "/home/blackbox/tools/ShadowClone/env/lib/python3.10/site-packages/lithops/serverless/serverless.py", line 113, in get_runtime_info
    return self.backend.get_runtime_info()
  File "/home/blackbox/tools/ShadowClone/env/lib/python3.10/site-packages/lithops/serverless/backends/aws_lambda/aws_lambda.py", line 695, in get_runtime_info
    raise Exception(
Exception: Python 3.10 is not available for AWS Lambda, please use one of ['3.6', '3.7', '3.8', '3.9'], or use a container runtime.

```

**Comment by JosepSampe** [comment]
The python 3.10 support has been added in master branch, but not yet released. 
It will be present in the next release

**Comment by sakyb7** [comment]
When it will release?

**Comment by JosepSampe** [comment]
We are working on fixing an issue in this AWS Lambda backend #1107, once fixed we will create a release

**Comment by JosepSampe** [comment]
@sakyb7 You can try master branch with:
```
pip install -U git+https://github.com/lithops-cloud/lithops.git@master
```
