### ISSUE TITLE
Deployment error when using Lithops with K8s + Redis

### ISSUE THREAD

**Issue by RaulGracia** [lithops-cloud/lithops#1133]
**Description of the problem**
Hi all,

I'm trying to deploy Lithops using a Kubernetes cluster plus Redis as storage backend. I think that I have made some progress, but I got an error that I think that may be useful to share here. Let me describe the scenario:

1) Kubernetes cluster is ready and Redis is deployed on it:
```
kubectl get services
NAME                    TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)          AGE
kubernetes              ClusterIP      192.168.2.1     <none>          443/TCP          3d
my-redis-headless       ClusterIP      None            <none>          6379/TCP         135m
my-redis-loadbalancer   LoadBalancer   192.168.2.112   xx.xxx.xxx.xx   6379:30547/TCP   120m
my-redis-master         ClusterIP      192.168.2.214   <none>          6379/TCP         135m
my-redis-replicas       ClusterIP      192.168.2.169   <none>          6379/TCP         135m
```

2) I'm deploying Lithops from my local machine, but Redis is accessible from both inside and outside the cluster (external IP):
```
xx.xxx.xxx.xx:6379> ping
PONG
```

3) I use this configuration file `~/.lithops/config`:
```
lithops: 
    backend: k8s
    storage: redis

k8s:
    kubecfg_path: /home/raul/.kube/config
    docker_server: docker.io
    docker_user: raulgracia
    docker_password: ------
    runtime: jsampe/lithops-default-k8s-runtime-v39:2.6.1.dev0

redis:
    host: xx.xxx.xxx.xx
    port: 6379
    password: -------
```

4) I then run `lithops test` and the process starts, but at some point there is an error in which, apparently, some metadata key for the job is expected to be stored in Redis, but it is not found:
```
2023-08-17 17:27:18,545 [INFO] config.py:141 -- Lithops v2.9.1.dev0 - Python3.10
2023-08-17 17:27:19,424 [INFO] redis.py:43 -- Redis client created - Host: xx.xxx.xxx.xx
2023-08-17 17:27:19,437 [INFO] k8s.py:81 -- Kubernetes Job client created - Namespace: default
2023-08-17 17:27:19,437 [INFO] invokers.py:108 -- ExecutorID 05be2a-0 | JobID A000 - Selected Runtime: docker.io/jsampe/lithops-default-k8s-runtime-v39:2.6.1.dev0 - 256MB
2023-08-17 17:27:20,455 [INFO] invokers.py:116 -- Runtime docker.io/jsampe/lithops-default-k8s-runtime-v39:2.6.1.dev0 with 256MB is not yet deployed
2023-08-17 17:27:20,455 [INFO] k8s.py:200 -- Deploying runtime: docker.io/jsampe/lithops-default-k8s-runtime-v39:2.6.1.dev0 - Memory: 256 Timeout: 600
2023-08-17 17:27:21,707 [INFO] k8s.py:371 -- Extracting metadata from: docker.io/jsampe/lithops-default-k8s-runtime-v39:2.6.1.dev0
Traceback (most recent call last):
  File "/usr/local/bin/lithops", line 33, in <module>
    sys.exit(load_entry_point('lithops==2.9.1.dev0', 'console_scripts', 'lithops')())
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/lithops-2.9.1.dev0-py3.10.egg/lithops/scripts/cli.py", line 179, in hello
    fexec.call_async(hello, username)
  File "/usr/local/lib/python3.10/dist-packages/lithops-2.9.1.dev0-py3.10.egg/lithops/executors.py", line 212, in call_async
    runtime_meta = self.invoker.select_runtime(job_id, runtime_memory)
  File "/usr/local/lib/python3.10/dist-packages/lithops-2.9.1.dev0-py3.10.egg/lithops/invokers.py", line 117, in select_runtime
    runtime_meta = self.compute_handler.deploy_runtime(self.runtime_name, runtime_memory, runtime_timeout)
  File "/usr/local/lib/python3.10/dist-packages/lithops-2.9.1.dev0-py3.10.egg/lithops/serverless/serverless.py", line 73, in deploy_runtime
    return self.backend.deploy_runtime(runtime_name, memory, timeout=timeout)
  File "/usr/local/lib/python3.10/dist-packages/lithops-2.9.1.dev0-py3.10.egg/lithops/serverless/backends/k8s/k8s.py", line 202, in deploy_runtime
    runtime_meta = self._generate_runtime_meta(docker_image_name)
  File "/usr/local/lib/python3.10/dist-packages/lithops-2.9.1.dev0-py3.10.egg/lithops/serverless/backends/k8s/k8s.py", line 442, in _generate_runtime_meta
    json_str = self.internal_storage.get_data(key=data_key)
  File "/usr/local/lib/python3.10/dist-packages/lithops-2.9.1.dev0-py3.10.egg/lithops/storage/storage.py", line 350, in get_data
    return self.storage.get_object(self.bucket, key, stream, extra_get_args)
  File "/usr/local/lib/python3.10/dist-packages/lithops-2.9.1.dev0-py3.10.egg/lithops/storage/storage.py", line 120, in get_object
    return self.storage_handler.get_object(bucket, key, stream, extra_get_args)
  File "/usr/local/lib/python3.10/dist-packages/lithops-2.9.1.dev0-py3.10.egg/lithops/storage/backends/redis/redis.py", line 104, in get_object
    raise StorageNoSuchKeyError(bucket_name, key)
lithops.storage.utils.StorageNoSuchKeyError: No such key /storage/lithops.jobs/lithops-worker-291dev0-a2b7c1e877.meta found in storage.
```

Note that I do see the Lithops job being deployed in Kubernetes as a pod, but after the crash it is cleaned up:
```
NAME                                           READY   STATUS    RESTARTS   AGE
lithops-worker-291dev0-a2b7c1e877-meta-j88xk   1/1     Running   0          5s
my-redis-master-0                              1/1     Running   0          131m
my-redis-replicas-0                            1/1     Running   0          131m
my-redis-replicas-1                            1/1     Running   0          130m
my-redis-replicas-2                            1/1     Running   0          129m
ubuntu                                         1/1     Running   0          22h
```

I wonder if there is something missing in my Redis configuration with respect to the "bucket" or "storage_bucket" parameter. Any help is appreciated, thanks!

**Comment by aitorarjona** [comment]
Hi @RaulGracia
can you print the logs from pod `lithops-worker-291dev0-a2b7c1e877-meta-j88xk`?

**Comment by JosepSampe** [comment]
Hi @RaulGracia! :)
Note that you are using Python3.10 and Lithops version 2.9.1.dev0
```
2023-08-17 17:27:18,545 [INFO] config.py:141 -- Lithops v2.9.1.dev0 - Python3.10
```

And the runtime you use was built for Python 3.9 and Lithops version 2.6.1.dev0
```
jsampe/lithops-default-k8s-runtime-v39:2.6.1.dev0
```

In the case of the kubernetes backend, the runtime must match both the python and lithops versions.
I just built this runtime for you, can you try with it?
```
jsampe/lithops-default-k8s-runtime-v310:2.9.1.dev0
```

Alternatively, you can [navigate to this folder](https://github.com/lithops-cloud/lithops/tree/master/runtime/kubernetes) and build your own default/custom runtime

**Comment by RaulGracia** [comment]
Thanks for the help guys!

@aitorarjona, at the time of the experiment, I couldn't get the logs for that pod, as the experiment kept failing shortly after.

@JosepSampe thanks, man! Yes, you are right, the problem was related to the mismatch of the runtime environment. I have tried again the same test, just using the new runtime and the command `lithops test` seems to work fine:

```
2023-08-22 09:13:48,451 [INFO] config.py:141 -- Lithops v2.9.1.dev0 - Python3.10
2023-08-22 09:13:49,488 [INFO] redis.py:43 -- Redis client created - Host: xx.xx.xx.xx
2023-08-22 09:13:49,502 [INFO] k8s.py:81 -- Kubernetes Job client created - Namespace: default
2023-08-22 09:13:49,503 [INFO] invokers.py:108 -- ExecutorID 66282f-0 | JobID A000 - Selected Runtime: docker.io/jsampe/lithops-default-k8s-runtime-v310:2.9.1.dev0 - 256MB
2023-08-22 09:13:50,515 [INFO] invokers.py:116 -- Runtime docker.io/jsampe/lithops-default-k8s-runtime-v310:2.9.1.dev0 with 256MB is not yet deployed
2023-08-22 09:13:50,516 [INFO] k8s.py:200 -- Deploying runtime: docker.io/jsampe/lithops-default-k8s-runtime-v310:2.9.1.dev0 - Memory: 256 Timeout: 600
2023-08-22 09:13:51,743 [INFO] k8s.py:371 -- Extracting metadata from: docker.io/jsampe/lithops-default-k8s-runtime-v310:2.9.1.dev0
2023-08-22 09:14:17,928 [INFO] invokers.py:172 -- ExecutorID 66282f-0 | JobID A000 - Starting function invocation: hello() - Total: 1 activations
2023-08-22 09:14:22,261 [INFO] invokers.py:208 -- ExecutorID 66282f-0 | JobID A000 - View execution logs at /tmp/lithops-raul/logs/66282f-0-A000.log
2023-08-22 09:14:22,261 [INFO] wait.py:98 -- ExecutorID 66282f-0 - Getting results from 1 function activations

  100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1  

2023-08-22 09:14:34,725 [INFO] executors.py:615 -- ExecutorID 66282f-0 - Cleaning temporary data

Hello raul! Lithops is working as expected :)
```

I will try to run some other stuff to see what happens, but so far it is working well. Thanks!!
