### ISSUE TITLE
Python 3.8.5 on mac - issues with COS SDK

### ISSUE THREAD

**Issue by gilv** [lithops-cloud/lithops#404]
I am not sure if it's COS SDK issue or Lithops issue. 
Issue happens on mac, Python 3.8.5, remote_invoker=False. 
(All is working with Python 3.7..5 or Python 3.8.5 with remote_invoker=True)

Running Lithops simple test

```
import lithops
import os
import json

iterdata = [1,2,3]

def my_map_function(data):
    return data + 7
     
if __name__ == '__main__':
    pw = lithops.FunctionExecutor(type="serverless", backend='ibm_cf', runtime = 'ibmfunctions/lithops-cf-3.8.5-2.2.1:1.0.3') 
    futures = pw.map(my_map_function, iterdata)
    print (pw.get_result())
    pw.clean()
```

```
Lithops v2.2.1 init for IBM Cloud Functions - Namespace: pywren_dev_us_east - Region: us_east
ExecutorID f06924/0 | JobID M000 - Selected Runtime: ibmfunctions/lithops-cf-3.8.5-2.2.1:1.0.3 - 256MB 
ExecutorID f06924/0 | JobID M000 - Uploading function and data - Total: 695.0B
Traceback (most recent call last):
  File "/Users/me/Dev/test.py", line 21, in <module>
    futures = pw.map(my_map_function, iterdata)
  File "/Users/me/.pyenv/versions/3.8.5/lib/python3.8/site-packages/lithops/executors.py", line 216, in map
    futures = self.invoker.run(job, runtime_memory)
  File "/Users/me/.pyenv/versions/3.8.5/lib/python3.8/site-packages/lithops/invokers.py", line 428, in run
    raise e
  File "/Users/me/.pyenv/versions/3.8.5/lib/python3.8/site-packages/lithops/invokers.py", line 374, in run
    self._start_invoker_process()
  File "/Users/me/.pyenv/versions/3.8.5/lib/python3.8/site-packages/lithops/invokers.py", line 242, in _start_invoker_process
    p.start()
  File "/Users/me/.pyenv/versions/3.8.5/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/me/.pyenv/versions/3.8.5/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/me/.pyenv/versions/3.8.5/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/me/.pyenv/versions/3.8.5/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/me/.pyenv/versions/3.8.5/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/me/.pyenv/versions/3.8.5/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/me/.pyenv/versions/3.8.5/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'ibm_botocore.client.S3'>: attribute lookup S3 on ibm_botocore.client failed
```
Is this related changes in #379 ?

@JosepSampe this summarise the issue. Do you know what might causing this?

**Comment by JosepSampe** [comment]
@gilv I'm investigating it

**Comment by JosepSampe** [comment]
@gilv All is working in my case with Python 3.8, so I guess it is related to MAC. 
It is very weird where the error is produced... The error is produced when the the invoker background process is started. This process does not receives at any time anything related to ibm_botocore. This process only receives json strings.
I do't have access to a MAC, so I can't replicate it.

**Comment by gilv** [comment]
@JosepSampe yes...it's Mac related

**Comment by gilv** [comment]
Also version 3.8.6 has the same issues

**Comment by gilv** [comment]
@JosepSampe when i think about, i can perfectly use cos-sdk from my laptop to access COS. So the only place where the issue happens is here

```
          forinv_id inrange(self.INVOKER_PROCESSES):
                p = mp.Process(target=self._run_invoker_process, args=(inv_id, ))
                self.invokers.append(p)
                p.daemon = True
                p.start()
```

**Comment by gilv** [comment]
@JosepSampe you think this is [relevant](https://stackoverflow.com/questions/8804830/python-multiprocessing-picklingerror-cant-pickle-type-function) ?

**Comment by JosepSampe** [comment]
In this code you posted, can you try changing  `mp.Process` to `Thread` ? this way we will know if you have the same issue using threads instead of processes. I guess it will work, but just to make it sure

> @JosepSampe you think this is [relevant](https://stackoverflow.com/questions/8804830/python-multiprocessing-picklingerror-cant-pickle-type-function) ?

Maybe, I can't test anything :/

**Comment by gilv** [comment]
@JosepSampe works like charm with

```
            for inv_id in range(self.INVOKER_PROCESSES):
                p = Thread(target=self._run_invoker_process, args=(inv_id, ))
                self.invokers.append(p)
                p.daemon = True
                p.start()
```

what does it mean? :)

**Comment by JosepSampe** [comment]
An `mp.Process` tries to load instantiated classes from main process into a separate process, and for some reason it fails in MAC and python3.8. A thread is executed in the same main process, so it doesn't have to load anything as all is already loaded, so this issue doen't appear.

I think for now we can add a workaround like:

```python
if mac_os and python3.8:
  use Thread
else:
  use mp.Process
```

**Comment by gilv** [comment]
@JosepSampe this?

```
    def _start_invoker_process(self):
        """
        Starts the invoker process responsible to spawn pending calls in background
        """
        ver = sys.version_info
        if self.is_lithops_worker or not is_unix_system() or platform=='darwin' and int(ver.major)>2:
            for inv_id in range(self.INVOKER_PROCESSES):
                p = Thread(target=self._run_invoker_process, args=(inv_id, ))
                self.invokers.append(p)
                p.daemon = True
                p.start()
        else:
            for inv_id in range(self.INVOKER_PROCESSES):
                p = mp.Process(target=self._run_invoker_process, args=(inv_id, ))
                self.invokers.append(p)
                p.daemon = True
                p.start()
```

**Comment by JosepSampe** [comment]
@gil Yes if it works for you. Where is `platform` variable defined?

**Comment by JosepSampe** [comment]
@gilv before  changing anything. can you try with this?: Delete all you added in the "if", and add at the begging of the document, below `import multiprocessing as mp:`
`multiprocessing.set_start_method("fork")`

**Comment by gilv** [comment]
@JosepSampe this one works also
```
import multiprocessing as mp
mp.set_start_method("fork")
```

**Comment by gilv** [comment]
@JosepSampe can i merge it?

**Comment by JosepSampe** [comment]
I think it is better to add the line here in line 35:
https://github.com/lithops-cloud/lithops/blob/master/lithops/invokers.py#L35

Test it and merge it ;)
