### ISSUE TITLE
GCP deployment

### ISSUE THREAD

**Issue by otrack** [lithops-cloud/lithops#429]
The documentation should indicate that the GCP Cloud Build API must be activated. 

After activating it, the command "lithops test" fails because requirements.txt is missing under /home/login/.local/lib/python3.8/site-packages/lithops/serverless/backends/gcp_functions.

When this problem is solved the command still fails. A full log is available below as well as the lithops configuration that was used.

===

lithops:
  storage: gcp_storage  
  storage_bucket: lithops
  
serverless:
  backend: gcp_functions
  runtime: python3.8

gcp:
  project_name : pro-project-137023
  service_account : lithops-executor[@]pro-project-137023.iam.gserviceaccount.com
  credentials_path : /home/login/.gcloud/lithops.json
  region : europe-west2

===

Traceback (most recent call last):
  File "/layers/google.python.functions-framework/functions-framework/bin/functions-framework", line 8, in <module>
    sys.exit(_cli())
  File "/layers/google.python.functions-framework/functions-framework/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/layers/google.python.functions-framework/functions-framework/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/layers/google.python.functions-framework/functions-framework/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/layers/google.python.functions-framework/functions-framework/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/layers/google.python.functions-framework/functions-framework/lib/python3.8/site-packages/functions_framework/_cli.py", line 37, in _cli
    app = create_app(target, source, signature_type)
  File "/layers/google.python.functions-framework/functions-framework/lib/python3.8/site-packages/functions_framework/__init__.py", line 172, in create_app
    spec.loader.exec_module(source_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/workspace/main.py", line 23, in <module>
    from lithops.config import cloud_logging_config
ImportError: cannot import name 'cloud_logging_config' from 'lithops.config' (/workspace/lithops/config.py)

**Comment by JosepSampe** [comment]
@otrack Fixed in #430 test master branch

**Comment by aitorarjona** [comment]
@otrack The issues have been fixed and merged into master in #430 and #431. Colud you install lithops from main branch and run `lithops test --debug` again to check if it has been solved for you? You should also run `lithops clean` before to delete the deployed runtime that has the issues. Thanks.

**Comment by otrack** [comment]
Sounds fine now. Thanks!
