### ISSUE TITLE
Exception in _future_timeout_checker

### ISSUE THREAD

**Issue by LachlanStuart** [lithops-cloud/lithops#483]
I found this in my server logs, and I think it explains some of the stalls I've seen when calling `executor.get_result`:

```
- lithops.standalone.standalone[Thread-1] - standalone.py:201 - ExecutorID b36c9a-3 | JobID M000 - Remote log monitor started
2020-12-03 17:16:45,665 - INFO - lithops.standalone.standalone[Thread-1] - standalone.py:225 - ExecutorID b36c9a-3 | JobID M000 - Running job
2020-12-03 17:16:45,665 - INFO - lithops.standalone.standalone[Thread-1] - standalone.py:227 - View execution logs at /tmp/lithops/logs/b36c9a-3-M000.log
2020-12-03 17:16:45,920 - INFO - lithops.invokers[Thread-1] - invokers.py:151 - ExecutorID b36c9a-3 | JobID M000 - _load_ds() Invocation done - Total: 1 activations
2020-12-03 17:16:45,921 - INFO - lithops.executors[Thread-1] - executors.py:364 - ExecutorID b36c9a-3 - Getting results...
Exception in thread Thread-54:
Traceback (most recent call last):
  File "/opt/dev/miniconda3/envs/sm38/lib/python3.8/site-packages/lithops/wait/wait_storage.py", line 281, in _future_timeout_checker
    raise TimeoutError('HANDLER', msg)
TimeoutError: [Errno HANDLER] The function did not run as expected.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/dev/miniconda3/envs/sm38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/dev/miniconda3/envs/sm38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/dev/miniconda3/envs/sm38/lib/python3.8/site-packages/lithops/wait/wait_storage.py", line 290, in _future_timeout_checker
    pickled_exception = str(pickle.dumps(sys.exc_info()))
TypeError: cannot pickle 'traceback' object
```

It seems both `wait_storage.py` and `wait_rabbitmq.py` have this line: `pickled_exception = str(pickle.dumps(sys.exc_info()))`

`sys.exc_info()` returns a `(exc_type, exc_value, exc_traceback)` tuple, and the `exc_traceback` part can't be pickled. I noticed that Lithops includes the `tblib` library for adding support for pickling `traceback`s, but `tblib` only seems to be installed on workers, not on the host.

**Comment by JosepSampe** [comment]
@LachlanStuart I added the pickling_support in both `wait_*.py` files.

It's a bit weird because I ran some test forcing this exception, and in my case it  raises and pickles the exception correctly, and I didn't have the  pickling_support anywhere in my local machine. 

In any case, it is  much better having it there to prevent possible pickling issues as in your case

**Comment by LachlanStuart** [comment]
Awesome, thanks @JosepSampe .

I find it a bit strange too. After finding this function exists, I'm surprised I haven't seen this exception message sooner, because I have been investigating cases where `get_result` has stalled and not recovered, even after several hours, due to unexpected VM shutdowns. This was the first time I saw this exception message, but I've had at least 2 other cases where there was no exception logged after 1 hour. I'll keep investigating.
