### ISSUE TITLE
Function call failed (500) - Retrying Request

### ISSUE THREAD

**Issue by csegarragonz** [lithops-cloud/lithops#586]
Hi!

I am trying to run Lithops on an Azure-managed k8s cluster through Knative. My config file looks like the following:
```yaml
lithops:
    storage: "azure_blob"
    storage_bucket: "storage"

serverless:
    backend: "knative"

knative:
    kubecfg_path: "/home/csegarra/.kube/config"
    istio_endpoint: "http://52.224.128.238:80"

azure_blob:
    storage_account: "lithops"
    storage_account_key:  <KEY>
```

As far as I can tell, `knative` works fine, and so does the storage (lithops installs the runtimes and job tmp files adequately). However, any execution will hang in the synchronisation point:
```bash
$ lithops test --debug
2021-03-08 08:53:29,386 [INFO] lithops.config -- Lithops v2.2.16
2021-03-08 08:53:29,386 [DEBUG] lithops.config -- Loading configuration
2021-03-08 08:53:29,389 [DEBUG] lithops.config -- Loading Serverless backend module: knative
2021-03-08 08:53:29,989 [DEBUG] lithops.config -- Loading Storage backend module: azure_blob
2021-03-08 08:53:30,267 [DEBUG] lithops.storage.backends.azure_blob.azure_blob -- Creating Azure Blob Storage client
2021-03-08 08:53:30,268 [INFO] lithops.storage.backends.azure_blob.azure_blob -- Azure Blob Storage client created
2021-03-08 08:53:30,316 [DEBUG] lithops.serverless.backends.knative.knative -- Loaded service host suffix: .default.52.224.128.238.xip.io
2021-03-08 08:53:30,316 [INFO] lithops.serverless.backends.knative.knative -- Knative client created - Istio Endpoint: http://52.224.128.238:80
2021-03-08 08:53:30,316 [DEBUG] lithops.invokers -- ExecutorID 123d6b-0 - Total available workers: 250
2021-03-08 08:53:30,319 [DEBUG] lithops.invokers -- ExecutorID 123d6b-0 - Serverless invoker created
2021-03-08 08:53:30,319 [INFO] lithops.executors -- Serverless Executor created with ID: 123d6b-0
2021-03-08 08:53:30,319 [INFO] lithops.invokers -- ExecutorID 123d6b-0 | JobID A000 - Selected Runtime: csegarragonz/lithops-knative-v38:2216 - 256MB 
2021-03-08 08:53:30,320 [DEBUG] lithops.storage.storage -- Runtime metadata found in local cache
2021-03-08 08:53:30,320 [DEBUG] lithops.job.job -- ExecutorID 123d6b-0 | JobID A000 - Serializing function and data
2021-03-08 08:53:30,322 [DEBUG] lithops.job.serialize -- Referenced modules: {'/home/csegarra/.local/lib/python3.8/site-packages/lithops/scripts/cli.py'}
2021-03-08 08:53:30,323 [DEBUG] lithops.job.serialize -- Modules to transmit: None
2021-03-08 08:53:30,323 [INFO] lithops.job.job -- ExecutorID 123d6b-0 | JobID A000 - Uploading function and data - Total: 775.0B
2021-03-08 08:53:30,768 [DEBUG] lithops.invokers -- ExecutorID 123d6b-0 - Invoker process 0 started
2021-03-08 08:53:30,768 [INFO] lithops.invokers -- ExecutorID 123d6b-0 | JobID A000 - Starting function invocation: hello() - Total: 1 activations
2021-03-08 08:53:30,769 [DEBUG] lithops.invokers -- ExecutorID 123d6b-0 | JobID A000 - Free workers: 250 - Going to invoke 1 function activations
2021-03-08 08:53:30,771 [DEBUG] lithops.invokers -- ExecutorID 123d6b-0 - Invoker process 1 started
2021-03-08 08:53:30,771 [DEBUG] lithops.serverless.backends.knative.knative -- ExecutorID 123d6b-0 | JobID A000 - Invoking function call 00000
2021-03-08 08:53:30,872 [DEBUG] lithops.invokers -- ExecutorID 123d6b-0 | JobID A000 - Starting job monitoring
2021-03-08 08:53:30,873 [INFO] lithops.executors -- ExecutorID 123d6b-0 - Getting results
2021-03-08 08:53:30,965 [DEBUG] lithops.serverless.backends.knative.knative -- ExecutorID 123d6b-0 | JobID A000 - Function call 00000 failed (500). Retrying request
2021-03-08 08:53:30,979 [DEBUG] lithops.serverless.backends.knative.knative -- ExecutorID 123d6b-0 | JobID A000 - Invoking function call 00000
2021-03-08 08:53:31,141 [DEBUG] lithops.serverless.backends.knative.knative -- ExecutorID 123d6b-0 | JobID A000 - Function call 00000 failed (500). Retrying request
2021-03-08 08:53:34,147 [DEBUG] lithops.serverless.backends.knative.knative -- ExecutorID 123d6b-0 | JobID A000 - Invoking function call 00000
2021-03-08 08:53:34,309 [DEBUG] lithops.serverless.backends.knative.knative -- ExecutorID 123d6b-0 | JobID A000 - Function call 00000 failed (500). Retrying request
2021-03-08 08:53:39,317 [DEBUG] lithops.serverless.backends.knative.knative -- ExecutorID 123d6b-0 | JobID A000 - Invoking function call 00000
2021-03-08 08:53:39,480 [DEBUG] lithops.serverless.backends.knative.knative -- ExecutorID 123d6b-0 | JobID A000 - Function call 00000 failed (500). Retrying request
2021-03-08 08:53:43,485 [DEBUG] lithops.serverless.backends.knative.knative -- ExecutorID 123d6b-0 | JobID A000 - Invoking function call 00000
2021-03-08 08:53:43,648 [DEBUG] lithops.serverless.backends.knative.knative -- ExecutorID 123d6b-0 | JobID A000 - Function call 00000 failed (500). Retrying request
2021-03-08 08:53:48,655 [DEBUG] lithops.serverless.backends.knative.knative -- ExecutorID 123d6b-0 | JobID A000 - Invoking function call 00000
2021-03-08 08:53:48,816 [DEBUG] lithops.serverless.backends.knative.knative -- ExecutorID 123d6b-0 | JobID A000 - Function call 00000 failed (500). Retrying request
2021-03-08 08:53:49,849 [INFO] lithops.executors -- ExecutorID 123d6b-0 - Cancelled - Total Activations not done: 1
2021-03-08 08:53:49,849 [DEBUG] lithops.invokers -- ExecutorID 123d6b-0 - Stopping invoker
2021-03-08 08:53:49,849 [DEBUG] lithops.invokers -- ExecutorID 123d6b-0 - Invoker process 1 finished

Aborted!
```
and it would keep trying forever. Any ideas about what may be causing this issue?

**Comment by JosepSampe** [comment]
@csegarragonz What instructions did you follow to install knative? If you delete the istio_endpoint from the config file, what is the output from Lithops?

**Comment by csegarragonz** [comment]
@JosepSampe I am using a custom install for `knative` (as I am benchmarking different systems, hence would like the same set up). I only install the `serving`, basically following [this](https://knative.dev/docs/install/any-kubernetes-cluster/#installing-the-serving-component) instructions.

The docker images _seem_ to be working fine, so I don't think it is a `tekton` issue (?), and `knative serving` works fine (at least the [hello world](https://knative.dev/docs/serving/samples/hello-world/helloworld-python/). Is the `eventing` component necessary?

If I remove the `istio_endpoint` from the config file, it uses a different port (32669 instead of 80) but the connection times out at the same point. I attach the log file:
```
2021-03-08 11:13:41,727 [INFO] lithops.config -- Lithops v2.2.16
2021-03-08 11:13:41,727 [DEBUG] lithops.config -- Loading configuration
2021-03-08 11:13:41,728 [DEBUG] lithops.config -- Loading Serverless backend module: knative
2021-03-08 11:13:42,101 [DEBUG] lithops.config -- Loading Storage backend module: azure_blob
2021-03-08 11:13:42,401 [DEBUG] lithops.storage.backends.azure_blob.azure_blob -- Creating Azure Blob Storage client
2021-03-08 11:13:42,402 [INFO] lithops.storage.backends.azure_blob.azure_blob -- Azure Blob Storage client created
2021-03-08 11:13:42,858 [DEBUG] lithops.serverless.backends.knative.knative -- Loaded service host suffix: .default.52.224.128.238.xip.io
2021-03-08 11:13:42,858 [INFO] lithops.serverless.backends.knative.knative -- Knative client created - Istio Endpoint: http://52.224.128.238:32669
2021-03-08 11:13:42,858 [DEBUG] lithops.invokers -- ExecutorID 2c1bd7-0 - Total available workers: 250
2021-03-08 11:13:42,862 [DEBUG] lithops.invokers -- ExecutorID 2c1bd7-0 - Serverless invoker created
2021-03-08 11:13:42,862 [INFO] lithops.executors -- Serverless Executor created with ID: 2c1bd7-0
2021-03-08 11:13:42,862 [INFO] lithops.invokers -- ExecutorID 2c1bd7-0 | JobID A000 - Selected Runtime: csegarragonz/lithops-knative-v38:2216 - 256MB 
2021-03-08 11:13:42,863 [DEBUG] lithops.storage.storage -- Runtime metadata found in local cache
2021-03-08 11:13:42,863 [DEBUG] lithops.job.job -- ExecutorID 2c1bd7-0 | JobID A000 - Serializing function and data
2021-03-08 11:13:42,866 [DEBUG] lithops.job.serialize -- Referenced modules: {'/home/csegarra/.local/lib/python3.8/site-packages/lithops/scripts/cli.py'}
2021-03-08 11:13:42,866 [DEBUG] lithops.job.serialize -- Modules to transmit: None
2021-03-08 11:13:42,866 [INFO] lithops.job.job -- ExecutorID 2c1bd7-0 | JobID A000 - Uploading function and data - Total: 775.0B
2021-03-08 11:13:43,395 [DEBUG] lithops.invokers -- ExecutorID 2c1bd7-0 - Invoker process 0 started
2021-03-08 11:13:43,395 [INFO] lithops.invokers -- ExecutorID 2c1bd7-0 | JobID A000 - Starting function invocation: hello() - Total: 1 activations
2021-03-08 11:13:43,398 [DEBUG] lithops.invokers -- ExecutorID 2c1bd7-0 - Invoker process 1 started
2021-03-08 11:13:43,412 [DEBUG] lithops.invokers -- ExecutorID 2c1bd7-0 | JobID A000 - Free workers: 250 - Going to invoke 1 function activations
2021-03-08 11:13:43,413 [DEBUG] lithops.serverless.backends.knative.knative -- ExecutorID 2c1bd7-0 | JobID A000 - Invoking function call 00000
2021-03-08 11:13:43,515 [DEBUG] lithops.invokers -- ExecutorID 2c1bd7-0 | JobID A000 - Starting job monitoring
2021-03-08 11:13:43,516 [INFO] lithops.executors -- ExecutorID 2c1bd7-0 - Getting results
exception calling callback for <Future at 0x7fa5953adbe0 state=finished raised TimeoutError>
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 328, in _invoke_callbacks
    callback(self)
  File "/home/csegarra/.local/lib/python3.8/site-packages/lithops/invokers.py", line 379, in _callback
    future.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/csegarra/.local/lib/python3.8/site-packages/lithops/invokers.py", line 272, in _invoke
    activation_id = self.compute_handler.invoke(job.runtime_name, job.runtime_memory, payload)
  File "/home/csegarra/.local/lib/python3.8/site-packages/lithops/serverless/serverless.py", line 50, in invoke
    return self.backend.invoke(runtime_name, memory, payload)
  File "/home/csegarra/.local/lib/python3.8/site-packages/lithops/serverless/backends/knative/knative.py", line 620, in invoke
    raise e
  File "/home/csegarra/.local/lib/python3.8/site-packages/lithops/serverless/backends/knative/knative.py", line 612, in invoke
    conn.request("POST", route, body=json.dumps(payload), headers=headers)
  File "/usr/lib/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1004, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 944, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 915, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.8/socket.py", line 807, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out
^C2021-03-08 11:10:25,225 [DEBUG] lithops.invokers -- ExecutorID 0552df-0 - Invoker process 0 finished
2021-03-08 11:10:25,225 [DEBUG] lithops.invokers -- ExecutorID 0552df-0 - Invoker process 1 finished
2021-03-08 11:10:25,225 [INFO] lithops.executors -- ExecutorID 0552df-0 - Cancelled - Total Activations not done: 1
2021-03-08 11:10:25,225 [DEBUG] lithops.invokers -- ExecutorID 0552df-0 - Stopping invoker
```

**Comment by JosepSampe** [comment]
When you ran the knative hello world, you invoked it using the dns or using the istio endpoint?

I mean, did you use this?: `curl http://helloworld-python.default.1.2.3.4.xip.io`
or something like this?: `curl -X GET -G -H "Host: helloworld-python.default.52.224.128.238.xip.io" http://52.224.128.238:31380/`

If you used the dns, could you try using the istio enpoint?

**Comment by csegarragonz** [comment]
I used the DNS. If I try the second option you give, it won't work unless I change the port to `80`. I.e. this works: 
```
curl -X GET -G -H "Host: helloworld-python.default.52.224.128.238.xip.io" http://52.224.128.238:80/
```

**Comment by JosepSampe** [comment]
Ok, this seems to be all ok. Let's check another thing. Could you provide the output from : `kubectl get ksvc -o wide`

**Comment by csegarragonz** [comment]
Sure!
```
NAME                                             URL                                                                                   LATESTCREATED                                          LATESTREADY                                            READY   REASON
csegarragonz--lithops-knative-v38--2216--256mb   http://csegarragonz--lithops-knative-v38--2216--256mb.default.52.224.128.238.xip.io   csegarragonz--lithops-knative-v38--2216--256mb-00001   csegarragonz--lithops-knative-v38--2216--256mb-00001   True    
helloworld-python                                http://helloworld-python.default.52.224.128.238.xip.io                                helloworld-python-00001                                helloworld-python-00001                                True    
```

**Comment by JosepSampe** [comment]
ok, the lithops service is correctly deployed. Try now:
`curl http://csegarragonz--lithops-knative-v38--2216--256mb.default.52.224.128.238.xip.io/preinstalls`
and:
`curl -X GET -G -H "Host: csegarragonz--lithops-knative-v38--2216--256mb.default.52.224.128.238.xip.io" http://52.224.128.238:80/preinstalls`

Both commands should return a list of python packages

**Comment by csegarragonz** [comment]
Indeed!

**Comment by JosepSampe** [comment]
Great! everything is looking good. I will investigate the possible causes of the 500 error and come back to you. thanks for the feedback.

**Comment by JosepSampe** [comment]
I ran some experiments in a brand new knative installation and seems that all is working properly.

Can you provide logs from the created pod(s)? Theoretically, if you run `lithops test` you will see some pods (kubectl get pods) even if a 500 error is produced. So check the logs from those pods with: `k logs <POD_NAME> -c user-container`

**Comment by csegarragonz** [comment]
Definately this was the right way to go. It seems that the `azure` is not installed in the runtime?
```
2021-03-09 06:25:14,723 [ERROR] lithops.storage.storage -- An exception was produced trying to create the 'azure_blob' storage backend
[2021-03-09 06:25:14,723] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/lithops/lithopsproxy.py", line 56, in run
    function_handler(message)
  File "/lithops/lithops/worker/handler.py", line 80, in function_handler
    internal_storage = InternalStorage(storage_config)
  File "/lithops/lithops/storage/storage.py", line 192, in __init__
    self.storage = Storage(storage_config=storage_config)
  File "/lithops/lithops/storage/storage.py", line 66, in __init__
    raise e
  File "/lithops/lithops/storage/storage.py", line 60, in __init__
    sb_module = importlib.import_module(module_location)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/lithops/lithops/storage/backends/azure_blob/__init__.py", line 1, in <module>
    from .azure_blob import AzureBlobStorageBackend as StorageBackend
  File "/lithops/lithops/storage/backends/azure_blob/azure_blob.py", line 19, in <module>
    from azure.storage.blob import BlobServiceClient
ModuleNotFoundError: No module named 'azure'
```

Note that the same `import` statement works fine in my local machine.

**Comment by JosepSampe** [comment]
I included the azure storage lib into the default knative runtime. Update to master branch and try again

**Comment by csegarragonz** [comment]
So the 500 disappeared, but then I am running into a different problem. Here are the logs for the execution:
```bash
$ cat /tmp/lithops/lithops-{...}.log
Activation: 'csegarragonz/lithops-knative-v38:latest' (e7371b308d6f)
[
    2021-03-10 06:34:14,101 [INFO] lithops.worker.handler -- Lithops v2.3.1dev0 - Starting execution
    2021-03-10 06:34:14,101 [INFO] lithops.worker.handler -- Execution ID: 73e73e-0-A000/00000
    2021-03-10 06:34:14,101 [DEBUG] lithops.worker.handler -- Runtime name: csegarragonz/lithops-knative-v38:latest
    2021-03-10 06:34:14,102 [DEBUG] lithops.worker.handler -- Runtime memory: 256MB
    2021-03-10 06:34:14,102 [DEBUG] lithops.worker.handler -- Function timeout: 595s
    2021-03-10 06:34:14,286 [DEBUG] lithops.storage.backends.azure_blob.azure_blob -- Creating Azure Blob Storage client
    2021-03-10 06:34:14,286 [INFO] lithops.storage.backends.azure_blob.azure_blob -- Azure Blob Storage client created
    2021-03-10 06:34:14,422 [DEBUG] lithops.worker.handler -- Starting JobRunner process
    2021-03-10 06:34:14,428 [DEBUG] lithops.worker.jobrunner -- Process started
    2021-03-10 06:34:14,428 [DEBUG] lithops.worker.jobrunner -- Getting function and modules
    2021-03-10 06:34:14,446 [DEBUG] lithops.worker.jobrunner -- Getting function data
    ----------------------- EXCEPTION !-----------------------
    Traceback (most recent call last):
      File "/lithops/lithops/worker/jobrunner.py", line 273, in run
        data = self._load_data()
      File "/lithops/lithops/worker/jobrunner.py", line 159, in _load_data
        loaded_data = pickle.loads(data_obj)
    _pickle.UnpicklingError: pickle data was truncated
    ----------------------------------------------------------
    2021-03-10 06:34:14,454 [DEBUG] lithops.worker.jobrunner -- Pickling exception
    2021-03-10 06:34:14,455 [INFO] lithops.worker.jobrunner -- Process finished
    2021-03-10 06:34:14,458 [DEBUG] lithops.worker.handler -- JobRunner process finished
]
```

And these are the ones from the log:
```
$ kubectl logs csegarragonz-{...} -c user-container
[2021-03-10 06:34:12 +0000] [1] [INFO] Starting gunicorn 20.0.4
[2021-03-10 06:34:12 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
[2021-03-10 06:34:12 +0000] [1] [INFO] Using worker: sync
[2021-03-10 06:34:12 +0000] [7] [INFO] Booting worker with pid: 7
2021-03-10 06:34:14,071 [INFO] lithops.worker -- Lithops v2.3.1dev0 - Starting Knative execution
2021-03-10 06:34:14,085 [INFO] lithops.worker.handler -- Starting 1 processes
2021-03-10 06:34:14,094 [INFO] lithops.worker.handler -- Going to execute job 73e73e-0-A000-00000
2021-03-10 06:34:14,098 [INFO] lithops.worker.handler -- Worker process 0 started
2021-03-10 06:34:14,101 [INFO] lithops.worker.handler -- Lithops v2.3.1dev0 - Starting execution
2021-03-10 06:34:14,101 [INFO] lithops.worker.handler -- Execution ID: 73e73e-0-A000/00000
2021-03-10 06:34:14,101 [DEBUG] lithops.worker.handler -- Runtime name: csegarragonz/lithops-knative-v38:latest
2021-03-10 06:34:14,102 [DEBUG] lithops.worker.handler -- Runtime memory: 256MB
2021-03-10 06:34:14,102 [DEBUG] lithops.worker.handler -- Function timeout: 595s
2021-03-10 06:34:14,286 [DEBUG] lithops.storage.backends.azure_blob.azure_blob -- Creating Azure Blob Storage client
2021-03-10 06:34:14,286 [INFO] lithops.storage.backends.azure_blob.azure_blob -- Azure Blob Storage client created
2021-03-10 06:34:14,422 [DEBUG] lithops.worker.handler -- Starting JobRunner process
2021-03-10 06:34:14,428 [DEBUG] lithops.worker.jobrunner -- Process started
2021-03-10 06:34:14,428 [DEBUG] lithops.worker.jobrunner -- Getting function and modules
2021-03-10 06:34:14,446 [DEBUG] lithops.worker.jobrunner -- Getting function data
----------------------- EXCEPTION !-----------------------
Traceback (most recent call last):
  File "/lithops/lithops/worker/jobrunner.py", line 273, in run
    data = self._load_data()
  File "/lithops/lithops/worker/jobrunner.py", line 159, in _load_data
    loaded_data = pickle.loads(data_obj)
_pickle.UnpicklingError: pickle data was truncated
----------------------------------------------------------
2021-03-10 06:34:14,454 [DEBUG] lithops.worker.jobrunner -- Pickling exception
2021-03-10 06:34:14,455 [INFO] lithops.worker.jobrunner -- Process finished
2021-03-10 06:34:14,458 [DEBUG] lithops.worker.handler -- JobRunner process finished
2021-03-10 06:34:14,460 [INFO] lithops.worker.handler -- Storing execution stats - Size: 2.3KiB
2021-03-10 06:34:30,059 [INFO] lithops.worker.handler -- Finished
XXX_THE_END_OF_AN_ACTIVATION_XXX
```

**Comment by JosepSampe** [comment]
This is the first time we see this kind of exception. Need further investigation. Just to put me in context, you are trying to run `lithops test --debug` command, right? on the client side, did you see any error in the lithops logs?

**Comment by csegarragonz** [comment]
Yes, this happened when runing `lithops test --debug` with the original config file I included. And I see the same error logs in the client. For completeness I am pasting the full logs here as well:
```
$ lithops test --debug
2021-03-10 10:39:16,949 [INFO] lithops.config -- Lithops v2.3.1dev0
2021-03-10 10:39:16,949 [DEBUG] lithops.config -- Loading configuration
2021-03-10 10:39:16,952 [DEBUG] lithops.config -- Loading Serverless backend module: knative
2021-03-10 10:39:17,667 [DEBUG] lithops.config -- Loading Storage backend module: azure_blob
2021-03-10 10:39:18,023 [DEBUG] lithops.storage.backends.azure_blob.azure_blob -- Creating Azure Blob Storage client
2021-03-10 10:39:18,024 [INFO] lithops.storage.backends.azure_blob.azure_blob -- Azure Blob Storage client created
2021-03-10 10:39:18,099 [DEBUG] lithops.serverless.backends.knative.knative -- Loaded service host suffix: .default.52.224.128.238.xip.io
2021-03-10 10:39:18,099 [INFO] lithops.serverless.backends.knative.knative -- Knative client created - Istio Endpoint: http://52.224.128.238:80
2021-03-10 10:39:18,099 [DEBUG] lithops.invokers -- ExecutorID c531ea-0 - Total available workers: 250
2021-03-10 10:39:18,149 [DEBUG] lithops.invokers -- ExecutorID c531ea-0 - Serverless invoker created
2021-03-10 10:39:18,149 [INFO] lithops.executors -- Serverless Executor created with ID: c531ea-0
2021-03-10 10:39:18,149 [INFO] lithops.invokers -- ExecutorID c531ea-0 | JobID A000 - Selected Runtime: csegarragonz/lithops-knative-v38:latest - 256MB 
2021-03-10 10:39:18,150 [DEBUG] lithops.storage.storage -- Runtime metadata found in local cache
2021-03-10 10:39:18,150 [DEBUG] lithops.job.job -- ExecutorID c531ea-0 | JobID A000 - Serializing function and data
2021-03-10 10:39:18,153 [DEBUG] lithops.job.serialize -- Referenced modules: {'/home/csegarra/.local/lib/python3.8/site-packages/lithops/scripts/cli.py'}
2021-03-10 10:39:18,154 [DEBUG] lithops.job.serialize -- Modules to transmit: None
2021-03-10 10:39:18,154 [INFO] lithops.job.job -- ExecutorID c531ea-0 | JobID A000 - Uploading function and data - Total: 775.0B
2021-03-10 10:39:18,604 [DEBUG] lithops.invokers -- ExecutorID c531ea-0 - Invoker process 0 started
2021-03-10 10:39:18,604 [INFO] lithops.invokers -- ExecutorID c531ea-0 | JobID A000 - Starting function invocation: hello() - Total: 1 activations
2021-03-10 10:39:18,605 [DEBUG] lithops.invokers -- ExecutorID c531ea-0 | JobID A000 - Chunksize: 1 - Worker processes: 1
2021-03-10 10:39:18,605 [DEBUG] lithops.invokers -- ExecutorID c531ea-0 | JobID A000 - Free workers: 250 - Going to run 1 activations in 1 workers
2021-03-10 10:39:18,607 [DEBUG] lithops.serverless.backends.knative.knative -- ExecutorID c531ea-0 | JobID A000 - Invoking function call 00000
2021-03-10 10:39:18,607 [DEBUG] lithops.invokers -- ExecutorID c531ea-0 - Invoker process 1 started
2021-03-10 10:39:18,708 [DEBUG] lithops.invokers -- ExecutorID c531ea-0 | JobID A000 - Starting job monitoring
2021-03-10 10:39:18,709 [INFO] lithops.invokers -- ExecutorID c531ea-0 | JobID A000 - View execution logs at /tmp/lithops/logs/c531ea-0-A000.log
2021-03-10 10:39:18,710 [INFO] lithops.executors -- ExecutorID c531ea-0 - Getting results
2021-03-10 10:39:37,089 [DEBUG] lithops.invokers -- ExecutorID c531ea-0 | JobID A000 - Calls 00000 invoked (18.483s) - Activation ID: 9bb0bf564f5f
2021-03-10 10:39:37,571 [DEBUG] lithops.invokers -- ExecutorID c531ea-0 | JobID A000 - Job monitoring finished
2021-03-10 10:39:37,673 [INFO] lithops.executors -- ExecutorID c531ea-0 - Cleaning temporary data
2021-03-10 10:39:37,681 [DEBUG] lithops.invokers -- ExecutorID c531ea-0 - Stopping invoker
2021-03-10 10:39:37,682 [DEBUG] lithops.invokers -- ExecutorID c531ea-0 - Invoker process 0 finished
2021-03-10 10:39:37,683 [DEBUG] lithops.invokers -- ExecutorID c531ea-0 - Invoker process 1 finished
2021-03-10 10:39:37,683 [WARNING] lithops.future -- ExecutorID c531ea-0 | JobID A000 - There was an exception - Activation ID: 9bb0bf564f5f
Traceback (most recent call last):
  File "/lithops/lithops/worker/jobrunner.py", line 273, in run
  File "/lithops/lithops/worker/jobrunner.py", line 159, in _load_data
_pickle.UnpicklingError: pickle data was truncated
```

**Comment by JosepSampe** [comment]
I've finally been able to replicate the issue, will submit a fix soon

**Comment by JosepSampe** [comment]
This should be fixed on master branch

**Comment by csegarragonz** [comment]
It does! Thank you vey much for your help these days!
