### ISSUE TITLE
AWS deployment error: InvalidCLientTokenId when calling GetCallerIdentity operation: The security token included in the request is invalid

### ISSUE THREAD

**Issue by Elaa-jamazi** [lithops-cloud/lithops#661]
I have been trying to use map-reduce on lithops but I was facing an error when I try to deploy it on AWS. I get "InvalidCLientTokenId when calling GetCallerIdentity operation: The security token included in the request is invalid". At first in my config file, I didn't include the token only the secret access key and access key id and I thought the problem was related to that so I added "session_token" to my config file and I still received the same error. I made sure I gave the correct permissions to lithops and the lambda and S3 roles. So, in your opinion what may be the problem?

**Comment by JosepSampe** [comment]
@Elaa-jamazi Can you post here your config file? (hiding your passwords). 

Can you run this simple example in DEBUG mode an post here the executions logs, including the exception?


```python
import lithops


def my_map_function(id, x):
    print("I'm activation number {}".format(id))
    return x + 7


if __name__ == "__main__":
    iterdata = [1, 2, 3, 4]
    fexec = lithops.FunctionExecutor(log_level='DEBUG')
    fexec.map(my_map_function, iterdata)
    print(fexec.get_result())
```

**Comment by Elaa-jamazi** [comment]
**These are the execution logs:** 
2021-06-08 14:37:03,273 [INFO] lithops.config -- Lithops v2.3.3
2021-06-08 14:37:03,273 [DEBUG] lithops.config -- Loading configuration from /home/elaa/lithops_project/.lithops_config
2021-06-08 14:37:03,274 [DEBUG] lithops.config -- Loading Serverless backend module: aws_lambda
2021-06-08 14:37:03,312 [DEBUG] lithops.config -- Loading Storage backend module: aws_s3
2021-06-08 14:37:03,313 [DEBUG] lithops.storage.backends.aws_s3.aws_s3 -- Creating S3 client
2021-06-08 14:37:03,313 [DEBUG] lithops.storage.backends.aws_s3.aws_s3 -- AWS S3 using access_key_id and secret_access_key
2021-06-08 14:37:03,362 [INFO] lithops.storage.backends.aws_s3.aws_s3 -- S3 Storage client created - Endpoint: https://s3.console.aws.amazon.com/s3/buckets/lithops-data-elaa?region=us-east-1&tab=objects
2021-06-08 14:37:03,362 [DEBUG] lithops.serverless.backends.aws_lambda.aws_lambda -- Creating AWS Lambda client
2021-06-08 14:37:03,362 [DEBUG] lithops.serverless.backends.aws_lambda.aws_lambda -- Creating Boto3 AWS Session and Lambda Client
2021-06-08 14:37:04,351 [ERROR] lithops.serverless.serverless -- There was an error trying to create the aws_lambda serverless backend
Traceback (most recent call last):
  File "debug.py", line 11, in <module>
    fexec = lithops.FunctionExecutor(log_level='DEBUG')
  File "/home/elaa/.local/lib/python3.8/site-packages/lithops/executors.py", line 120, in __init__
    self.compute_handler = ServerlessHandler(serverless_config, self.internal_storage)
  File "/home/elaa/.local/lib/python3.8/site-packages/lithops/serverless/serverless.py", line 44, in __init__
    raise e
  File "/home/elaa/.local/lib/python3.8/site-packages/lithops/serverless/serverless.py", line 39, in __init__
    self.backend = ServerlessBackend(self.config[self.backend_name], internal_storage)
  File "/home/elaa/.local/lib/python3.8/site-packages/lithops/serverless/backends/aws_lambda/aws_lambda.py", line 80, in __init__
    self.account_id = sts_client.get_caller_identity()["Account"]
  File "/home/elaa/.local/lib/python3.8/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/elaa/.local/lib/python3.8/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidClientTokenId) when calling the GetCallerIdentity operation: The security token included in the request is invalid.

**Comment by aitorarjona** [comment]
Hello @Elaa-jamazi 
It seems that the endpoint for S3 is wrong.

Please refere to the documentation to determine the correct endpoint:
https://github.com/lithops-cloud/lithops/blob/master/config/storage/aws_s3.md
https://docs.aws.amazon.com/general/latest/gr/rande.html
It is not necessary to enter any token key in the configuration file as authentication is handled internally by the aws Python library.

In your case, since you're using region `us-east-1`, the s3 endpoint wold be `https://s3.us-east-1.amazonaws.com`.

Could you change the endpoint and try again?
I hope this solves your problem. Thanks.

**Comment by Elaa-jamazi** [comment]
Hello! Thank you for your answer, I applied the changes you suggested and that helped with the S3 error however now I am getting a new error about an InvalidCLientTokenId as you can see in the screenshot. I checked again with my access and secret keys and they were correct I didn't make any error with them. In your opinion, what can be the cause of this error.  
![Screenshot from 2021-06-09 10-19-10](https://user-images.githubusercontent.com/44344844/121319121-30c5ec00-c90c-11eb-9b35-61ed5f7dcb22.png)

**Comment by aitorarjona** [comment]
@Elaa-jamazi I think your account lacks permissions to access STS service, which is used to retrieve the account ID. You can add permissions to your account to access STS. On the IAM console, go to your user and add an **inline policy**. Then select STS and read access to GetCallerIdentity, or just paste this JSON on the JSON tab:
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "sts:GetCallerIdentity",
            "Resource": "*"
        }
    ]
}
```
Then create the policy and check if it has been atached to your user.
Your user also needs permissions for S3 and Lambda (and ECR if you will use a container runtime). Please check that you account has read and write access to all these services.

**Comment by Elaa-jamazi** [comment]
Apparently I don't have the permission through my AWS educate account to change the STS access. I am trying to change that. Meanwhile, I wanted to ask if the map_reduce_cos_bucket.py example is applicable on S3 buckets, since I can't try it directly myself. Would providing a link to an S3 bucket in the code be enough or is there other changes I should apply?

**Comment by aitorarjona** [comment]
Hi @Elaa-jamazi, I've added a new parameter for `aws` in config to put the account directly. This prevents using STS if it is not available as your case. Please install lithops from the main branch:

`pip install -U git+https://github.com/lithops-cloud/lithops`

then add `account_id` in `aws` section in your config file. Your account number is a 12-digit number, you can find it in the IAM section on the AWS web console:

```yaml
aws:
  access_key_id: AKIAIOSFODNN7EXAMPLE
  secret_access_key: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  account_id: XXXXXXXXXXXX
```
