### ISSUE TITLE
LitHops 2.3.4 code engine - Unable to extract Python preinstalled modules from the runtime

### ISSUE THREAD

**Issue by ethilesen** [lithops-cloud/lithops#673]
Hi,

I'm testing to run the latest version on code engine in Frankfurt - tried us-south as well with same issue..
2021-06-10 11:13:03,512 [INFO] lithops.config -- Lithops v2.3.4
2021-06-10 11:13:03,928 [INFO] lithops.storage.backends.ibm_cos.ibm_cos -- IBM COS Storage client created - Region: eu-de
2021-06-10 11:13:03,930 [INFO] lithops.serverless.backends.code_engine.code_engine -- IBM Code Engine client created - Region: eu-de
2021-06-10 11:13:03,930 [INFO] lithops.executors -- Serverless Executor created with ID: 512e8f-0
2021-06-10 11:13:03,930 [INFO] lithops.invokers -- ExecutorID 512e8f-0 | JobID M000 - Selected Runtime: ibmfunctions/lithops-ce-v385:232 - 256MB
2021-06-10 11:13:04,240 [INFO] lithops.invokers -- Runtime ibmfunctions/lithops-ce-v385:232 with 256MB is not yet installed
2021-06-10 11:13:04,725 [INFO] lithops.serverless.backends.code_engine.code_engine -- Extracting Python modules from: ibmfunctions/lithops-ce-v385:232
Traceback (most recent call last):
  File "/Users/espenthilesen/Developer/lithops/test.py", line 36, in <module>
    lt.map(add_value,  iterdata)
  File "/Users/espenthilesen/miniconda3/lib/python3.7/site-packages/lithops/executors.py", line 227, in map
    runtime_meta = self.invoker.select_runtime(job_id, runtime_memory)
  File "/Users/espenthilesen/miniconda3/lib/python3.7/site-packages/lithops/invokers.py", line 107, in select_runtime
    runtime_meta = self.compute_handler.create_runtime(self.runtime_name, runtime_memory, runtime_timeout)
  File "/Users/espenthilesen/miniconda3/lib/python3.7/site-packages/lithops/serverless/serverless.py", line 73, in create_runtime
    return self.backend.create_runtime(runtime_name, memory, timeout=timeout)
  File "/Users/espenthilesen/miniconda3/lib/python3.7/site-packages/lithops/serverless/backends/code_engine/code_engine.py", line 212, in create_runtime
    runtime_meta = self._generate_runtime_meta(docker_image_name, memory)
  File "/Users/espenthilesen/miniconda3/lib/python3.7/site-packages/lithops/serverless/backends/code_engine/code_engine.py", line 570, in _generate_runtime_meta
    raise Exception("Unable to extract Python preinstalled modules from the runtime")
Exception: Unable to extract Python preinstalled modules from the runtime

Any idea why this doesn't  work - only try to run the "hello" sample...

**Comment by ethilesen** [comment]
Found this in the job run:
lithops-runtime-preinstalls-1-0/ibmfunctions--lithops-ce-embl-v385--233--256mb:    
2021-06-10 09:27:49,471 [INFO] lithops.worker -- Lithops v2.3.3 - Generating metadata  
2021-06-10 09:27:54,796 [ERROR] lithops.storage.storage -- An exception was produced trying to create the 'ibm_cos' storage backend  
Traceback (most recent call last):  
  File "/lithops/lithopsentry.py", line 139, in <module>  
    main_job(sys.argv[1:][0], sys.argv[1:][1])  
  File "/lithops/lithopsentry.py", line 113, in main_job  
    runtime_packages(payload)  
  File "/lithops/lithopsentry.py", line 98, in runtime_packages  
    internal_storage = InternalStorage(payload)  
  File "/lithops/lithops/storage/storage.py", line 192, in __init__  
    self.storage = Storage(storage_config=storage_config)  
  File "/lithops/lithops/storage/storage.py", line 66, in __init__  
    raise e  
  File "/lithops/lithops/storage/storage.py", line 62, in __init__  
    self.storage_handler = StorageBackend(self.storage_config[self.backend])  
  File "/lithops/lithops/storage/backends/ibm_cos/ibm_cos.py", line 87, in __init__  
    token, token_expiry_time = iam_token_manager.get_token()  
  File "/lithops/lithops/util/ibm_token_manager.py", line 59, in get_token  
    self._generate_new_token()  
  File "/lithops/lithops/util/ibm_token_manager.py", line 50, in _generate_new_token  
    dump_yaml_config(self._token_filename, token_data)  
  File "/lithops/lithops/config.py", line 51, in dump_yaml_config  
    import yaml  
ModuleNotFoundError: No module named 'yaml'

**Comment by gilv** [comment]
@ethilesen i see that you use Lithops 2.3.4 but runtime is not for 2.3.4
Use runtime `ibmfunctions/lithops-ce-v385:234` for Lithops 2.3.4.

**Comment by gilv** [comment]
@JosepSampe any other ideas?

**Comment by ethilesen** [comment]
Tanks... du you have a list of all the 2.3.4 pre build images ?
