### ISSUE TITLE
Different behavior on the local environment and in the CF

### ISSUE THREAD

**Issue by sergii-mamedov** [lithops-cloud/lithops#724]
In METASPACE we are trying to upgrade from version 2.2.14 to 2.3.5. Now I am faced with an error that is reproduced only when running in CF. When I run the code locally, I don't see any problems. It also seems that the stack trace of the error is incomplete.

```
2021-07-25 12:48:32,049 - WARNING - lithops-daemon[Thread-1] - lithops.py:51 - Lithops annotation failed, retrying.
Traceback (most recent call last):
  File "/opt/dev/metaspace/metaspace/engine/sm/engine/daemons/lithops.py", line 81, in _callback
    self._manager.annotate_lithops(ds=ds, del_first=msg.get('del_first', False))
  File "/opt/dev/metaspace/metaspace/engine/sm/engine/daemons/dataset_manager.py", line 113, in annotate_lithops
    ServerAnnotationJob(executor, ds, perf).run()
  File "/opt/dev/metaspace/metaspace/engine/sm/engine/annotation_lithops/annotation_job.py", line 311, in run
    self.results_dfs, self.png_cobjs = self.pipe(**kwargs)
  File "/opt/dev/metaspace/metaspace/engine/sm/engine/annotation_lithops/pipeline.py", line 98, in __call__
    self.prepare_results(use_cache=use_cache)
  File "/opt/dev/metaspace/metaspace/engine/sm/engine/annotation_lithops/cache.py", line 81, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/dev/metaspace/metaspace/engine/sm/engine/annotation_lithops/pipeline.py", line 183, in prepare_results
    self.results_dfs, self.png_cobjs = filter_results_and_make_pngs(
  File "/opt/dev/metaspace/metaspace/engine/sm/engine/annotation_lithops/prepare_results.py", line 103, in filter_results_and_make_pngs
    png_cobjs = fexec.map(save_png_chunk, jobs, include_modules=['png'])
  File "/opt/dev/metaspace/metaspace/engine/sm/engine/annotation_lithops/executor.py", line 268, in map
    raise exc
  File "/opt/dev/metaspace/metaspace/engine/sm/engine/annotation_lithops/executor.py", line 301, in run
    futures = executor.map(
  File "/opt/dev/miniconda3/envs/sm38/lib/python3.8/site-packages/lithops/executors.py", line 244, in map
    job = create_map_job(config=self.config,
AttributeError: 'NoneType' object has no attribute 'startswith'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/dev/metaspace/metaspace/engine/sm/engine/queue.py", line 430, in get_message
    self._callback(msg)
  File "/opt/dev/metaspace/metaspace/engine/sm/engine/daemons/lithops.py", line 104, in _callback
    raise AnnotationError(ds_id=msg['ds_id'], traceback=format_exc(chain=False)) from e
sm.engine.errors.AnnotationError: Annotation failed (ds_id=2021-07-25_12h47m10s)
```

The error manifests itself when [this function is called](https://github.com/metaspace2020/metaspace/blob/master/metaspace/engine/sm/engine/annotation_lithops/prepare_results.py#L91). There is a feeling that this is related to the storage object, but when I run it in CF mode, I cannot do a full debug to find the reason. Could you take a look at this, maybe this is a lithops bug or give me a way to solve this problem.

**Comment by JosepSampe** [comment]
@sergii-mamedov I think it fails [here](https://github.com/lithops-cloud/lithops/blob/master/lithops/job/partitioner.py#L46). But if it fails here this means that iterdata might be empty. Could you verify/post here the content of `jobs` variable from [here](https://github.com/metaspace2020/metaspace/blob/master/metaspace/engine/sm/engine/annotation_lithops/prepare_results.py#L91)?

**Comment by sergii-mamedov** [comment]
@JosepSampe 
Yes, I also thought about this variable. Initially, we had a list of lists there, but following your documentation, I changed it to a [list of tuples](https://github.com/metaspace2020/metaspace/pull/901/files#diff-1dc8227bb32fcebb2e0262873a9299cc57dfee9f35580d66de09491edbf54079R38).
By adding the following logging both in local mode and in SF:
```
    logger.info(type(jobs))
    logger.info(jobs)
```

i see the following data:
```
2021-07-26 17:14:27,560 - INFO - annotation-pipeline[Thread-1] - prepare_results.py:78 - <class 'list'>
2021-07-26 17:14:27,560 - INFO - annotation-pipeline[Thread-1] - prepare_results.py:79 - [(           n_pixels  ...      cost
formula_i            ...          
214753          233  ...  101278.0
216035          219  ...  101264.0
216260          256  ...  101301.0
217473           98  ...  101143.0
268090          402  ...  101447.0
...             ...  ...       ...
41677            96  ...  101141.0
48820           210  ...  101255.0
78570            17  ...  101062.0
75342            21  ...    1066.0
91564            12  ...    1057.0

[134 rows x 3 columns],)]
```

**Comment by JosepSampe** [comment]
@sergii-mamedov Ah ok, you are sending de `df` directly to the function in an arg, so lithops can't fail [here](https://github.com/lithops-cloud/lithops/blob/master/lithops/job/partitioner.py#L46).

What is the asterisk (*) in the function signature? if you delete it what happens?

**Comment by JosepSampe** [comment]
@sergii-mamedov I ran some tests with a dataframe and all them work. Can you test them too?

```python
import pandas as pd

def save_png_chunk(df: pd.DataFrame, *, storage: Storage):
    print(df)

if __name__ == "__main__":

    data = {'Name': ['Tom', 'Joseph', 'Krish', 'John'], 'Age': [20, 21, 19, 18]}  
    dframe = pd.DataFrame(data)
    fexec = lithops.FunctionExecutor(backend='ibm_cf', storage='ibm_cos', log_level='INFO')
    fexec.map(save_png_chunk, [(dframe,), (dframe,)])
    fexec.get_result()
```

**Comment by sergii-mamedov** [comment]
@JosepSampe 
on the machine where I am seeing the problem
```
2021-07-26 17:47:17,603 [INFO] lithops.config -- Lithops v2.3.5
2021-07-26 17:47:17,662 [INFO] lithops.storage.backends.ibm_cos.ibm_cos -- IBM COS Storage client created - Region: eu-de
2021-07-26 17:47:18,031 [INFO] lithops.serverless.backends.ibm_cf.ibm_cf -- IBM CF client created - Region: eu-de - Namespace: env-staging
2021-07-26 17:47:18,031 [INFO] lithops.executors -- Function executor for ibm_cf created with ID: cc6391-0
2021-07-26 17:47:18,031 [INFO] lithops.invokers -- ExecutorID cc6391-0 | JobID M000 - Selected Runtime: lithopscloud/ibmcf-python-v38 - 256MB
2021-07-26 17:47:18,312 [INFO] lithops.invokers -- Runtime lithopscloud/ibmcf-python-v38 with 256MB is not yet installed
2021-07-26 17:47:18,312 [INFO] lithops.serverless.backends.ibm_cf.ibm_cf -- Creating new Lithops runtime based on Docker image lithopscloud/ibmcf-python-v38
/opt/dev/miniconda3/envs/sm38/lib/python3.8/inspect.py:350: FutureWarning: _AXIS_NAMES has been deprecated.
  value = getattr(object, key)
/opt/dev/miniconda3/envs/sm38/lib/python3.8/inspect.py:350: FutureWarning: _AXIS_NUMBERS has been deprecated.
  value = getattr(object, key)
/opt/dev/miniconda3/envs/sm38/lib/python3.8/inspect.py:350: FutureWarning: _AXIS_NAMES has been deprecated.
  value = getattr(object, key)
/opt/dev/miniconda3/envs/sm38/lib/python3.8/inspect.py:350: FutureWarning: _AXIS_NUMBERS has been deprecated.
  value = getattr(object, key)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-85ad30f31dfa> in <module>
      9     dframe = pd.DataFrame(data)
     10     fexec = lithops.FunctionExecutor(backend='ibm_cf', storage='ibm_cos', log_level='INFO', config=config)
---> 11     fexec.map(save_png_chunk, [(dframe,), (dframe,)])
     12     fexec.get_result()
     13 

/opt/dev/miniconda3/envs/sm38/lib/python3.8/site-packages/lithops/executors.py in map(self, map_function, map_iterdata, chunksize, worker_processes, extra_args, extra_env, runtime_memory, chunk_size, chunk_n, obj_chunk_size, obj_chunk_number, timeout, invoke_pool_threads, include_modules, exclude_modules)
    242         runtime_meta = self.invoker.select_runtime(job_id, runtime_memory)
    243 
--> 244         job = create_map_job(config=self.config,
    245                              internal_storage=self.internal_storage,
    246                              executor_id=self.executor_id,

/opt/dev/miniconda3/envs/sm38/lib/python3.8/site-packages/lithops/job/job.py in create_map_job(config, internal_storage, executor_id, job_id, map_function, iterdata, runtime_meta, runtime_memory, extra_env, include_modules, exclude_modules, execution_timeout, chunksize, worker_processes, extra_args, obj_chunk_size, obj_chunk_number, chunk_size, chunk_n, invoke_pool_threads)
     70     # ########
     71 
---> 72     job = _create_job(config=config,
     73                       internal_storage=internal_storage,
     74                       executor_id=executor_id,

/opt/dev/miniconda3/envs/sm38/lib/python3.8/site-packages/lithops/job/job.py in _create_job(config, internal_storage, executor_id, job_id, func, iterdata, runtime_meta, runtime_memory, extra_env, include_modules, exclude_modules, execution_timeout, host_job_meta, chunksize, worker_processes, invoke_pool_threads)
    236     job_serialize_start = time.time()
    237     serializer = SerializeIndependent(runtime_meta['preinstalls'])
--> 238     func_and_data_ser, mod_paths = serializer([func] + iterdata, inc_modules, exc_modules)
    239     data_strs = func_and_data_ser[1:]
    240     data_size_bytes = sum(len(x) for x in data_strs)

/opt/dev/miniconda3/envs/sm38/lib/python3.8/site-packages/lithops/job/serialize.py in __call__(self, list_of_objs, include_modules, exclude_modules)
     63             if module_name == '__main__':
     64                 continue
---> 65             origin = importlib.util.find_spec(module_name).origin
     66             direct_modules.add(origin if origin not in ['built-in', None] else module_name)
     67             self._modulemgr.add(module_name)

/opt/dev/miniconda3/envs/sm38/lib/python3.8/importlib/util.py in find_spec(name, package)
     88 
     89     """
---> 90     fullname = resolve_name(name, package) if name.startswith('.') else name
     91     if fullname not in sys.modules:
     92         parent_name = fullname.rpartition('.')[0]

AttributeError: 'NoneType' object has no attribute 'startswith'

```

**Comment by JosepSampe** [comment]
@sergii-mamedov So I think the issue could be fixed on master branch. Is it possible for you to test it with it? @gilv If it works we can prepare a new release

**Comment by sergii-mamedov** [comment]
@JosepSampe Of course I will be happy to help. Since this fix is important to me.

**Comment by JosepSampe** [comment]
@sergii-mamedov Moreover, could you edit this file /opt/dev/miniconda3/envs/sm38/lib/python3.8/site-packages/lithops/job/serialize.py and add a `print(module_name)` between lines 64 and 65? and post here the output

**Comment by sergii-mamedov** [comment]
@JosepSampe 
```
collections.abc
pandas.core.groupby.generic
pandas.core.indexes.base
urllib
pandas.core.dtypes.dtypes
numpy
itertools
pandas.core.arrays.datetimes
pandas.core.internals.construction
pandas._libs.tslibs.nattype
numpy.ma
pandas._libs.tslibs.offsets
pandas.plotting._core
pandas.core.indexes.datetimes
pandas._typing
pandas.io.formats.format
pandas._libs.ops
re
pandas.core.aggregation
importlib
pathlib
pandas.core.generic
pandas.core.series
pandas._config.config
pandas._libs.tslibs.timestamps
pandas.core.window
pandas.util._decorators
pandas.core.dtypes.missing
pandas
pandas.core.window.ewm
datetime
pandas.core.internals.blocks
pandas.core.ops
pandas.core.tools.datetimes
urllib.parse
pandas.core.arrays.categorical
pandas.io.formats.info
pandas.io.feather_format
pandas.core.internals
pandas.io.parquet
pandas.core.window.expanding
pandas.core.tools.timedeltas
pandas.core.indexes.api
pandas._libs.lib
pandas.core.tools
pandas.core.arrays.numpy_
warnings
pandas.io.formats.console
pandas.io.pickle
copy
pandas.core.computation.eval
_io
pandas.util._validators
pandas._libs.tslibs
pandas.core.ops.invalid
pandas.core.ops.missing
collections
pandas.core.indexing
numbers
pandas.compat
pandas.core.ops.dispatch
pandas.core.ops.methods
pandas.core.base
pandas.io.stata
pandas.core.missing
pandas.core.common
pandas._libs.tslibs.period
pandas._libs.tslibs.vectorized
pandas._libs.interval
pandas._libs.missing
pandas.core.computation
pandas._libs.algos
functools
dataclasses
pandas._libs.tslibs.np_datetime
pandas.core.indexes
mmap
numpy.core.multiarray
pandas.core.arrays
pandas.core.dtypes.common
pandas.compat._optional
pandas._libs
pandas.core.indexes.multi
pandas.core.indexes.range
pandas.core.nanops
pandas.core.frame
operator
json
pandas._libs.hashtable
pandas.core.reshape.melt
pandas.core.dtypes.base
distutils
weakref
pandas.core.computation.parsing
pandas.core.dtypes.inference
pandas.core.reshape
typing
os
pandas.core.dtypes.generic
_operator
pandas.io
pandas.core.reshape.merge
pandas.core.ops.roperator
pandas.core.sorting
pandas.core.window.rolling
pandas.core.reshape.reshape
pandas.core.ops.array_ops
numpy.core.fromnumeric
pandas.core
pandas.errors
pandas.core.arrays.base
pkg_resources
urllib.request
unicodedata
None
```

**Comment by JosepSampe** [comment]
Thanks @sergii-mamedov. So yes, this should work with master branch

**Comment by sergii-mamedov** [comment]
@JosepSampe very good!
When are you planning the next release?

**Comment by JosepSampe** [comment]
@gilv Could we prepare a new release?

**Comment by sergii-mamedov** [comment]
@JosepSampe 
I tried processing our data on the version from the master branch - everything worked successfully in the CF. Thanks for you help.

**Comment by gilv** [comment]
@JosepSampe yes, will release it right now

**Comment by JosepSampe** [comment]
@sergii-mamedov version 2.4.0 is ready
