### ISSUE TITLE
missing token on refresh

### ISSUE THREAD

**Issue by gilv** [lithops-cloud/lithops#751]
The following error reported 
```
Traceback (most recent call last):
  File "/opt/dev/miniconda3/envs/sm38/lib/python3.8/site-packages/lithops/serverless/backends/code_engine/code_engine.py", line 72, in __init__
    config.load_kube_config(config_file=self.kubecfg_path)
  File "/opt/dev/miniconda3/envs/sm38/lib/python3.8/site-packages/kubernetes/config/kube_config.py", line 798, in load_kube_config
    loader.load_and_set(config)
  File "/opt/dev/miniconda3/envs/sm38/lib/python3.8/site-packages/kubernetes/config/kube_config.py", line 576, in load_and_set
    self._load_authentication()
  File "/opt/dev/miniconda3/envs/sm38/lib/python3.8/site-packages/kubernetes/config/kube_config.py", line 280, in _load_authentication
    if self._load_auth_provider_token():
  File "/opt/dev/miniconda3/envs/sm38/lib/python3.8/site-packages/kubernetes/config/kube_config.py", line 299, in _load_auth_provider_token
    return self._load_oid_token(provider)
  File "/opt/dev/miniconda3/envs/sm38/lib/python3.8/site-packages/kubernetes/config/kube_config.py", line 403, in _load_oid_token
    self._refresh_oidc(provider)
  File "/opt/dev/miniconda3/envs/sm38/lib/python3.8/site-packages/kubernetes/config/kube_config.py", line 459, in _refresh_oidc
    refresh = request.refresh_token(
  File "/opt/dev/miniconda3/envs/sm38/lib/python3.8/site-packages/requests_oauthlib/oauth2_session.py", line 446, in refresh_token
    self.token = self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/opt/dev/miniconda3/envs/sm38/lib/python3.8/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 421, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/opt/dev/miniconda3/envs/sm38/lib/python3.8/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 431, in parse_token_response
    validate_token_parameters(params)
oauthlib.oauth2.rfc6749.errors.MissingTokenError: (missing_token) Missing access token parameter.
```

Lithops version 2.4.1. Occurs from time to time, probably every 5-10 launches.
@JosepSampe any ideas?

**Comment by JosepSampe** [comment]
@gilv How CE is configured? using kubecfg file? or using naespace_id? Can you provide lithops debig logs to see when it fails?

**Comment by sergii-mamedov** [comment]
@JosepSampe Now I have for any execution this error:

```
2021-08-31 23:06:50,620 - ERROR - lithops-daemon[Thread-1] - queue.py:432 -  [x] Failed: {"ds_id": "2021-08-26_11h36m32s", "ds_name": "dataset_04", "action": "annotate", "del_first": true, "force": false, "email": "sergii.mamedov@embl.de", "retry_attempt": 1}
2021-08-31 23:06:50,620 - CRITICAL - lithops-daemon[Thread-1] - lithops.py:60 - Lithops annotation failed. Falling back to Spark
Traceback (most recent call last):
  File "/opt/dev/miniconda3/envs/sm38/lib/python3.8/site-packages/lithops/serverless/backends/code_engine/code_engine.py", line 612, in _create_config_map
    self.core_api.create_namespaced_config_map(
  File "/opt/dev/miniconda3/envs/sm38/lib/python3.8/site-packages/kubernetes/client/api/core_v1_api.py", line 6630, in create_namespaced_config_map
    return self.create_namespaced_config_map_with_http_info(namespace, body, **kwargs)  # noqa: E501
  File "/opt/dev/miniconda3/envs/sm38/lib/python3.8/site-packages/kubernetes/client/api/core_v1_api.py", line 6725, in create_namespaced_config_map_with_http_info
    return self.api_client.call_api(
  File "/opt/dev/miniconda3/envs/sm38/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "/opt/dev/miniconda3/envs/sm38/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
  File "/opt/dev/miniconda3/envs/sm38/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 391, in request
    return self.rest_client.POST(url,
  File "/opt/dev/miniconda3/envs/sm38/lib/python3.8/site-packages/kubernetes/client/rest.py", line 274, in POST
    return self.request("POST", url,
  File "/opt/dev/miniconda3/envs/sm38/lib/python3.8/site-packages/kubernetes/client/rest.py", line 233, in request
    raise ApiException(http_resp=r)
kubernetes.client.exceptions.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Date': 'Tue, 31 Aug 2021 21:06:50 GMT', 'Content-Type': 'application/json', 'Content-Length': '345', 'Connection': 'keep-alive', 'Audit-Id': '0c4ada5d-f105-4508-a602-6f1129ea376f', 'Cache-Control': 'no-cache, private', 'X-Kubernetes-Pf-Flowschema-Uid': '05dc5f92-6c95-416b-b707-da00a57e0adc', 'X-Kubernetes-Pf-Prioritylevel-Uid': '8d40cc3d-a5c4-47ee-8978-ec5f7a197920', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'X-Content-Type-Options': 'nosniff', 'Content-Security-Policy': "default-src 'none'; frame-ancestors 'none'", 'X-XSS-Protection': '1; mode=block'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"configmaps \"lithops-7d2d1e-0-m000-configmap\" is forbidden: exceeded quota: 5s42h2uzmkv, requested: configmaps=1, used: configmaps=25, limited: configmaps=25","reason":"Forbidden","details":{"name":"lithops-7d2d1e-0-m000-configmap","kind":"configmaps"},"code":403}
```

I am using `kubecfg file`. I tried to re-generate it - the same situation.

**Comment by JosepSampe** [comment]
@gilv Apart of this error, kubecfg file in CE produce some other errors, and this is something we cannot control in Lithops since the file is generated by IBM. So, as you already have the IBM IAM API KEY configured, I suggest to [configure CE using the namespace ID](https://github.com/lithops-cloud/lithops/blob/master/config/compute/code_engine.md#option-1-ibm-iam) to avoid all these issues.

**Comment by gilv** [comment]
@JosepSampe right! ...i now realize that @sergii-mamedov doesn't use it.
@sergii-mamedov you need your config to be of the form
```
code_engine:
    namespace: <YOUR NAME SPACE ID>
    region:  your region
```
Please follow the link @JosepSampe posted above.

**Comment by sergii-mamedov** [comment]
@gilv @JosepSampe I have the same error ((

**Comment by sergii-mamedov** [comment]
I tried the simplest example to rule out the problem from the METASPACE side:
```
import lithops

iterdata = ['Gil', 'Dana', 'John', 'Scott']

def add_value(name):
    return 'Hello ' + name

if __name__ == '__main__':
    lt = lithops.FunctionExecutor(
      backend='code_engine',
      runtime='ibmfunctions/lithops-ce-v385:241',
      log_level='DEBUG')
    lt.map(add_value, iterdata)
    print(lt.get_result())
```
Exeption:
```
2021-09-06 01:19:57,646 [INFO] lithops.config -- Lithops v2.4.1
2021-09-06 01:19:57,646 [DEBUG] lithops.config -- Loading configuration from /home/finve/Documents/embl_code/metaspace/metaspace/engine/sm/engine/annotation_lithops/.lithops_config
2021-09-06 01:19:57,687 [DEBUG] lithops.config -- Loading Serverless backend module: code_engine
2021-09-06 01:19:57,958 [DEBUG] lithops.config -- Loading Storage backend module: ibm_cos
2021-09-06 01:19:57,983 [DEBUG] lithops.storage.backends.ibm_cos.ibm_cos -- Creating IBM COS client
2021-09-06 01:19:57,983 [DEBUG] lithops.storage.backends.ibm_cos.ibm_cos -- Set IBM COS Endpoint to https://s3.eu-de.cloud-object-storage.appdomain.cloud
2021-09-06 01:19:57,983 [DEBUG] lithops.storage.backends.ibm_cos.ibm_cos -- Using access_key and secret_key
2021-09-06 01:19:58,013 [INFO] lithops.storage.backends.ibm_cos.ibm_cos -- IBM COS Storage client created - Region: eu-de
2021-09-06 01:19:58,013 [DEBUG] lithops.serverless.backends.code_engine.code_engine -- Creating IBM Code Engine client
2021-09-06 01:19:58,021 [DEBUG] lithops.serverless.backends.code_engine.code_engine -- Set namespace to xxxxxxxxxxx
2021-09-06 01:19:58,021 [DEBUG] lithops.serverless.backends.code_engine.code_engine -- Set cluster to https://proxy.eu-de.codeengine.cloud.ibm.com
2021-09-06 01:19:58,021 [INFO] lithops.serverless.backends.code_engine.code_engine -- IBM Code Engine client created - Region: eu-de
2021-09-06 01:19:58,022 [DEBUG] lithops.invokers -- ExecutorID 3f4e9a-0 - Total workers: 1000
2021-09-06 01:19:58,022 [DEBUG] lithops.executors -- Function executor for code_engine created with ID: 3f4e9a-0
2021-09-06 01:19:58,022 [INFO] lithops.invokers -- ExecutorID 3f4e9a-0 | JobID M000 - Selected Runtime: ibmfunctions/lithops-ce-v385:241 - 256MB
2021-09-06 01:19:58,022 [DEBUG] lithops.storage.storage -- Runtime metadata not found in local cache. Retrieving it from storage
2021-09-06 01:19:58,022 [DEBUG] lithops.storage.storage -- Trying to download runtime metadata from: ibm_cos://metaspace-env-staging-temp/lithops.runtimes/2.4.1/code_engine/eu-de/xxxxxxxxxxx/ibmfunctions--lithops-ce-v385--241--256mb.meta.json
2021-09-06 01:19:58,418 [DEBUG] lithops.storage.storage -- Runtime metadata not found in storage
2021-09-06 01:19:58,418 [INFO] lithops.invokers -- Runtime ibmfunctions/lithops-ce-v385:241 with 256MB is not yet installed
2021-09-06 01:19:58,419 [DEBUG] lithops.serverless.backends.code_engine.code_engine -- Creating new Lithops runtime based on Docker image: ibmfunctions/lithops-ce-v385:241
2021-09-06 01:19:58,652 [DEBUG] lithops.serverless.backends.code_engine.code_engine -- Job Definition ibmfunctions--lithops-ce-v385--241--256mb created
2021-09-06 01:19:58,652 [INFO] lithops.serverless.backends.code_engine.code_engine -- Extracting Python modules from: ibmfunctions/lithops-ce-v385:241
2021-09-06 01:19:58,663 [DEBUG] lithops.serverless.backends.code_engine.code_engine -- Generate ConfigMap ibmfunctions--lithops-ce-v385--241--256mb-configmap for namespace xxxxxxxxxxxx
2021-09-06 01:19:58,869 [DEBUG] lithops.serverless.backends.code_engine.code_engine -- Creating a configmap failed with 403 Forbidden
Traceback (most recent call last):
  File "/home/finve/Documents/embl_code/metaspace/metaspace/engine/venv/lib/python3.8/site-packages/lithops/serverless/backends/code_engine/code_engine.py", line 612, in _create_config_map
    self.core_api.create_namespaced_config_map(
  File "/home/finve/Documents/embl_code/metaspace/metaspace/engine/venv/lib/python3.8/site-packages/kubernetes/client/api/core_v1_api.py", line 6630, in create_namespaced_config_map
    return self.create_namespaced_config_map_with_http_info(namespace, body, **kwargs)  # noqa: E501
  File "/home/finve/Documents/embl_code/metaspace/metaspace/engine/venv/lib/python3.8/site-packages/kubernetes/client/api/core_v1_api.py", line 6725, in create_namespaced_config_map_with_http_info
    return self.api_client.call_api(
  File "/home/finve/Documents/embl_code/metaspace/metaspace/engine/venv/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "/home/finve/Documents/embl_code/metaspace/metaspace/engine/venv/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
  File "/home/finve/Documents/embl_code/metaspace/metaspace/engine/venv/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 391, in request
    return self.rest_client.POST(url,
  File "/home/finve/Documents/embl_code/metaspace/metaspace/engine/venv/lib/python3.8/site-packages/kubernetes/client/rest.py", line 274, in POST
    return self.request("POST", url,
  File "/home/finve/Documents/embl_code/metaspace/metaspace/engine/venv/lib/python3.8/site-packages/kubernetes/client/rest.py", line 233, in request
    raise ApiException(http_resp=r)
kubernetes.client.exceptions.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Date': 'Sun, 05 Sep 2021 22:19:58 GMT', 'Content-Type': 'application/json', 'Content-Length': '385', 'Connection': 'keep-alive', 'Audit-Id': '82fdae74-07c2-4504-9652-db6242ac6dcb', 'Cache-Control': 'no-cache, private', 'X-Kubernetes-Pf-Flowschema-Uid': '05dc5f92-6c95-416b-b707-da00a57e0adc', 'X-Kubernetes-Pf-Prioritylevel-Uid': '8d40cc3d-a5c4-47ee-8978-ec5f7a197920', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'X-Content-Type-Options': 'nosniff', 'Content-Security-Policy': "default-src 'none'; frame-ancestors 'none'", 'X-XSS-Protection': '1; mode=block'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"configmaps \"ibmfunctions--lithops-ce-v385--241--256mb-configmap\" is forbidden: exceeded quota: xxxxxxx, requested: configmaps=1, used: configmaps=25, limited: configmaps=25","reason":"Forbidden","details":{"name":"ibmfunctions--lithops-ce-v385--241--256mb-configmap","kind":"configmaps"},"code":403}



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/home/finve/Documents/embl_code/metaspace/metaspace/engine/venv/lib/python3.8/site-packages/lithops/executors.py", line 239, in map
    runtime_meta = self.invoker.select_runtime(job_id, runtime_memory)
  File "/home/finve/Documents/embl_code/metaspace/metaspace/engine/venv/lib/python3.8/site-packages/lithops/invokers.py", line 122, in select_runtime
    runtime_meta = self.compute_handler.create_runtime(self.runtime_name, runtime_memory, runtime_timeout)
  File "/home/finve/Documents/embl_code/metaspace/metaspace/engine/venv/lib/python3.8/site-packages/lithops/serverless/serverless.py", line 73, in create_runtime
    return self.backend.create_runtime(runtime_name, memory, timeout=timeout)
  File "/home/finve/Documents/embl_code/metaspace/metaspace/engine/venv/lib/python3.8/site-packages/lithops/serverless/backends/code_engine/code_engine.py", line 210, in create_runtime
    runtime_meta = self._generate_runtime_meta(docker_image_name, memory)
  File "/home/finve/Documents/embl_code/metaspace/metaspace/engine/venv/lib/python3.8/site-packages/lithops/serverless/backends/code_engine/code_engine.py", line 526, in _generate_runtime_meta
    config_map = self._create_config_map(payload, jobdef_name)
  File "/home/finve/Documents/embl_code/metaspace/metaspace/engine/venv/lib/python3.8/site-packages/lithops/serverless/backends/code_engine/code_engine.py", line 622, in _create_config_map
    raise Exception('Failed to create ConfigMap')
Exception: Failed to create ConfigMap
``

`Is it possible that something is wrong with our account settings?

**Comment by JosepSampe** [comment]
@sergii-mamedov Seems now the config is ok, but you exceeded your ConfigMap quota, which is limited to 25.
You must delete all unnecessary configmaps in your account using `kubectl` command. 
First set your kubecfg file. Then use `kubectl get configmap` to see all your deployed configmaps. Then use `kubectl delete configmap xxxxx` to delete all unnecessary configmaps one by one.

**Comment by sergii-mamedov** [comment]
@JosepSampe Yes, I have already figured out that the problem is the ConfigMap overflow. I removed unneeded entries manually via the UI. But it seems that lithops, when the task fails, does not delete the ConfigMap after itself. Can you confirm or disprove my hypothesis?

**Comment by JosepSampe** [comment]
@sergii-mamedov In the current lithops version configmaps are deleted even when an error is produced. However, it is possible that older lithops version had this issue.

**Comment by sergii-mamedov** [comment]
@JosepSampe I tested yesterday. One of the launches got a MemoryError:
```
Activation: 'metaspace2020/metaspace-lithops-ce:1.8.6.9' (393e5cfad1c4)
[
    2021-09-06 14:53:06,333 [INFO] lithops.worker.handler -- Lithops v2.4.1 - Starting Code Engine (Job) execution
    2021-09-06 14:53:06,333 [INFO] lithops.worker.handler -- Execution ID: 367861-10-M007/00000
    2021-09-06 14:53:07,229 [INFO] lithops.worker.jobrunner -- Going to execute 'save_png_chunk()'
    ---------------------- FUNCTION LOG ----------------------
    2021-09-06 14:58:26,828 [ERROR] lithops.worker.handler -- No completion message received from JobRunner process
    ----------------------- EXCEPTION !-----------------------
    Traceback (most recent call last):
      File "/lithops/lithops/worker/handler.py", line 183, in run_job
        raise MemoryError('HANDLER', msg)
    MemoryError: ('HANDLER', 'Function exceeded maximum memory and was killed')
    ----------------------------------------------------------
]
```
However, ConfigMap `lithops-72f2b4-6-m008-configmap` was not deleted:
```
$ ibmcloud ce configmap list
Listing configmaps...
OK

Name                              Data  Age  

lithops-367861-10-m007-configmap  1     18h  
```

**Comment by gilv** [comment]
@JosepSampe how is that config maps doesn't deleted for them? it's deleted automatically...

**Comment by gilv** [comment]
@JosepSampe may be phases that includes cloudobject are not clean them?

**Comment by JosepSampe** [comment]
In my case the configmap is deleted:
```
2021-09-09 12:27:00,808 [DEBUG] lithops.monitor -- ExecutorID 01f4c5-0 - Storage job monitor finished
2021-09-09 12:27:00,884 [INFO] lithops.executors -- ExecutorID 01f4c5-0 - Cleaning temporary data
2021-09-09 12:27:00,888 [DEBUG] lithops.serverless.backends.code_engine.code_engine -- Deleting jobrun lithops-01f4c5-0-m000
2021-09-09 12:27:01,206 [DEBUG] lithops.serverless.backends.code_engine.code_engine -- Deleting ConfigMap lithops-01f4c5-0-m000-configmap for namespace aqqtvod1txv
2021-09-09 12:27:01,447 [WARNING] lithops.future -- ExecutorID 01f4c5-0 | JobID M000 - There was an exception - Activation ID: fc367db94eab
2021-09-09 12:27:01,447 [WARNING] lithops.future -- Exception: MemoryError - Function exceeded maximum memory and was killed
```

@sergii-mamedov can you post client logs?

**Comment by gilv** [comment]
@JosepSampe when we use cloudobject to pass between stages of executions, can data_cleaner be disabled?

**Comment by sergii-mamedov** [comment]
@JosepSampe In our lithops config `data_cleaner` is True. After last test, number of config maps has increased:

```
finve@laptop:~$ ibmcloud ce configmap list
Listing configmaps...
OK

Name                              Data  Age  
lithops-1b941a-10-m004-configmap  1     46h  
lithops-367861-10-m007-configmap  1     2d20h  
lithops-5298ce-6-m004-configmap   1     45h  
lithops-b2d4c3-10-m001-configmap  1     24h  
lithops-b2d4c3-6-m014-configmap   1     42h  
lithops-d41c98-2-m013-configmap   1     44h  
lithops-efcd36-0-m014-configmap   1     45h  
lithops-efcd36-4-m013-configmap   1     44h 
```

**Comment by gilv** [comment]
@JosepSampe any ideas? It also deleted for me...

**Comment by gilv** [comment]
@sergii-mamedov so you run a "job" that has multiple Lithops invocations...between invocations you use CloudObjects. When the "job" finished, you see more ConfigMaps than you had before the job. Is this correct? How more, like 1 or plenty of ConfigMaps that didn't deleted?

**Comment by sergii-mamedov** [comment]
@gilv correct

**Comment by JosepSampe** [comment]
@sergii-mamedov Could you post execution logs?

**Comment by JosepSampe** [comment]
Is it possible that this issue is related to the other issue you have about tokens that expire when you run large workflows? because if the token expired, then Lithops is unable to delete configmaps.

**Comment by gilv** [comment]
@sergii-mamedov ^^ see Josep's question please

**Comment by JosepSampe** [comment]
@sergii-mamedov I fixed the issues related to "token expired" in #758 . Might it fix this issue too. Try with master branch.

**Comment by sergii-mamedov** [comment]
@JosepSampe I ran a dozen datasets with the current version of lithops. I will report the results.

**Comment by sergii-mamedov** [comment]
@JosepSampe , @gilv I ran ten datasets - so far so good. Could you make a new release, as I cannot use the master branch to release METASPACE.

**Comment by gilv** [comment]
@sergii-mamedov will create new release later today

**Comment by sergii-mamedov** [comment]
@gilv perfect

**Comment by sergii-mamedov** [comment]
@JosepSampe I think it might be closed.
