### ISSUE TITLE
Problem with ip_address and private_ip keys for IBM VPC

### ISSUE THREAD

**Issue by sergii-mamedov** [lithops-cloud/lithops#849]
When trying to upgrade to 2.5.6, I found this stack trace:
```
$ python script.py 
2021-11-11 14:42:04,745 [INFO] lithops.config -- Lithops v2.5.6
2021-11-11 14:42:04,764 [INFO] lithops.storage.backends.ibm_cos.ibm_cos -- IBM COS client created - Region: eu-de
2021-11-11 14:42:05,141 [INFO] lithops.serverless.backends.ibm_cf.ibm_cf -- IBM CF client created - Region: eu-de - Namespace: env-staging
2021-11-11 14:42:05,142 [INFO] lithops.config -- Lithops v2.5.6
2021-11-11 14:42:05,593 [INFO] lithops.storage.backends.ibm_cos.ibm_cos -- IBM COS client created - Region: eu-de
2021-11-11 14:42:05,600 [INFO] lithops.standalone.backends.ibm_vpc.ibm_vpc -- IBM VPC client created - Region: eu-de
Traceback (most recent call last):
  File "script.py", line 18, in <module>
    job = LocalAnnotationJob(imzml_file, ibd_file, db_files, ds_config)
  File "/home/ubuntu/gil/metaspace/metaspace/engine/sm/engine/annotation_lithops/annotation_job.py", line 201, in __init__
    self.pipe = Pipeline(
  File "/home/ubuntu/gil/metaspace/metaspace/engine/sm/engine/annotation_lithops/pipeline.py", line 70, in __init__
    self.executor = executor or Executor(lithops_config)
  File "/home/ubuntu/gil/metaspace/metaspace/engine/sm/engine/annotation_lithops/executor.py", line 164, in __init__
    'ibm_vpc': lithops.StandaloneExecutor(
  File "/home/ubuntu/gil/metaspace/metaspace/engine/venv/lib/python3.8/site-packages/lithops/executors.py", line 751, in __init__
    super().__init__(config=config,
  File "/home/ubuntu/gil/metaspace/metaspace/engine/venv/lib/python3.8/site-packages/lithops/executors.py", line 154, in __init__
    self.invoker = create_invoker(
  File "/home/ubuntu/gil/metaspace/metaspace/engine/venv/lib/python3.8/site-packages/lithops/invokers.py", line 45, in create_invoker
    return BatchInvoker(
  File "/home/ubuntu/gil/metaspace/metaspace/engine/venv/lib/python3.8/site-packages/lithops/invokers.py", line 243, in __init__
    self.compute_handler.init()
  File "/home/ubuntu/gil/metaspace/metaspace/engine/venv/lib/python3.8/site-packages/lithops/standalone/standalone.py", line 64, in init
    self.backend.init()
  File "/home/ubuntu/gil/metaspace/metaspace/engine/venv/lib/python3.8/site-packages/lithops/standalone/backends/ibm_vpc/ibm_vpc.py", line 266, in init
    self.master.public_ip = self.config['private_ip']
KeyError: 'private_ip'
```
when trying to replace the `ip_address` key in the config file with `private_ip` - I see the following exeption:
```
Traceback (most recent call last):
  File "script.py", line 18, in <module>
    job = LocalAnnotationJob(imzml_file, ibd_file, db_files, ds_config)
  File "/home/ubuntu/gil/metaspace/metaspace/engine/sm/engine/annotation_lithops/annotation_job.py", line 201, in __init__
    self.pipe = Pipeline(
  File "/home/ubuntu/gil/metaspace/metaspace/engine/sm/engine/annotation_lithops/pipeline.py", line 70, in __init__
    self.executor = executor or Executor(lithops_config)
  File "/home/ubuntu/gil/metaspace/metaspace/engine/sm/engine/annotation_lithops/executor.py", line 164, in __init__
    'ibm_vpc': lithops.StandaloneExecutor(
  File "/home/ubuntu/gil/metaspace/metaspace/engine/venv/lib/python3.8/site-packages/lithops/executors.py", line 751, in __init__
    super().__init__(config=config,
  File "/home/ubuntu/gil/metaspace/metaspace/engine/venv/lib/python3.8/site-packages/lithops/executors.py", line 123, in __init__
    self.config = default_config(copy.deepcopy(config), config_ow)
  File "/home/ubuntu/gil/metaspace/metaspace/engine/venv/lib/python3.8/site-packages/lithops/config.py", line 214, in default_config
    sb_config.load_config(config_data)
  File "/home/ubuntu/gil/metaspace/metaspace/engine/venv/lib/python3.8/site-packages/lithops/standalone/backends/ibm_vpc/config.py", line 73, in load_config
    raise Exception(msg)
Exception: 'ip_address' is mandatory in 'ibm_vpc' section of the configuration
```

As far as I can see, `private_ip` was added to [this PR](https://github.com/lithops-cloud/lithops/commit/87e9265e7b781c0b25a7431ee1b27cc2b20d0692). @JosepSampe  Could you please clarify the situation?

I also have a question, why is it necessary to specify information about the VPC in the config file for IBM CF? Can't I exclusively use CF or CE without VPC?

**Comment by JosepSampe** [comment]
Fixed in #850

**Comment by JosepSampe** [comment]
> I also have a question, why is it necessary to specify information about the VPC in the config file for IBM CF? Can't I exclusively use CF or CE without VPC?

Can you provide an example?

**Comment by sergii-mamedov** [comment]
> Can you provide an example?

I double-checked. On our side, the CF and VPC are initialized at the same time.

**Comment by sergii-mamedov** [comment]
@giarve  could you create a new release?

**Comment by JosepSampe** [comment]
@sergii-mamedov There is already a new release
