### ISSUE TITLE
AttributeError: 'KnativeServingBackend' object has no attribute 'coreV1Api'

### ISSUE THREAD

**Issue by FTWH** [lithops-cloud/lithops#914]
2022-05-17 20:36:50,287 [INFO] lithops.config -- Lithops v2.6.0
2022-05-17 20:36:50,463 [INFO] lithops.storage.backends.redis.redis -- Redis client created - Host: 192.168.122.1
2022-05-17 20:36:50,503 [INFO] lithops.serverless.backends.knative.knative -- Knative client created - Istio Endpoint: http://192.168.122.11:31380
2022-05-17 20:36:50,503 [INFO] lithops.invokers -- ExecutorID 3f162b-0 | JobID M000 - Selected Runtime: 201980951/lithops-knative-v38:260 - 256MB
2022-05-17 20:36:50,504 [INFO] lithops.invokers -- Runtime XXX/lithops-knative-v38:260 with 256MB is not yet deployed
2022-05-17 20:36:50,579 [INFO] lithops.serverless.backends.knative.knative -- Building default runtime
Traceback (most recent call last):
  File "sample.py", line 21, in <module>
    fexec.map(is_inside, part_count)
  File "/home/XXX/anaconda3/envs/XXX/lib/python3.8/site-packages/lithops/executors.py", line 258, in map
    runtime_meta = self.invoker.select_runtime(job_id, runtime_memory)
  File "/home/XXX/anaconda3/envs/XXX/lib/python3.8/site-packages/lithops/invokers.py", line 120, in select_runtime
    runtime_meta = self.compute_handler.deploy_runtime(self.runtime_name, runtime_memory, runtime_timeout)
  File "/home/XXX/anaconda3/envs/XXX/lib/python3.8/site-packages/lithops/serverless/serverless.py", line 73, in deploy_runtime
    return self.backend.deploy_runtime(runtime_name, memory, timeout=timeout)
  File "/home/XXX/anaconda3/envs/XXX/lib/python3.8/site-packages/lithops/serverless/backends/knative/knative.py", line 533, in deploy_runtime
    self._create_container_registry_secret()
  File "/home/XXX/anaconda3/envs/XXX/lib/python3.8/site-packages/lithops/serverless/backends/knative/knative.py", line 413, in _create_container_registry_secret
    self.coreV1Api.delete_namespaced_secret("lithops-regcred", self.namespace)
AttributeError: 'KnativeServingBackend' object has no attribute 'coreV1Api'

My config is as follows:
<img width="189" alt="image" src="https://user-images.githubusercontent.com/71968506/168813386-e01ce063-c973-436d-9b7f-1f9e7cb8b853.png">

My code is as follows:
<img width="516" alt="image" src="https://user-images.githubusercontent.com/71968506/168813511-b9b2d3f3-2e44-4b9b-941b-4f59d6e44439.png">

**Comment by JosepSampe** [comment]
@FTWH PR #915  should fix the issue

**Comment by FTWH** [comment]
> @FTWH PR #915 should fix the issue

`2022-05-18 08:53:47,958 [INFO] lithops.serverless.backends.knative.knative -- Building default runtime
Traceback (most recent call last):
  File "sample.py", line 21, in <module>
    fexec.map(is_inside, part_count)
  File "/home/xxx/anaconda3/envs/faas-scaler/lib/python3.8/site-packages/lithops-2.6.1.dev0-py3.8.egg/lithops/executors.py", line 258, in map
    runtime_meta = self.invoker.select_runtime(job_id, runtime_memory)
  File "/home/xxx/anaconda3/envs/faas-scaler/lib/python3.8/site-packages/lithops-2.6.1.dev0-py3.8.egg/lithops/invokers.py", line 120, in select_runtime
    runtime_meta = self.compute_handler.deploy_runtime(self.runtime_name, runtime_memory, runtime_timeout)
  File "/home/xxx/anaconda3/envs/faas-scaler/lib/python3.8/site-packages/lithops-2.6.1.dev0-py3.8.egg/lithops/serverless/serverless.py", line 73, in deploy_runtime
    return self.backend.deploy_runtime(runtime_name, memory, timeout=timeout)
  File "/home/xxx/anaconda3/envs/faas-scaler/lib/python3.8/site-packages/lithops-2.6.1.dev0-py3.8.egg/lithops/serverless/backends/knative/knative.py", line 534, in deploy_runtime
    self._create_service(docker_image_name, memory, timeout)
  File "/home/xxx/anaconda3/envs/faas-scaler/lib/python3.8/site-packages/lithops-2.6.1.dev0-py3.8.egg/lithops/serverless/backends/knative/knative.py", line 464, in _create_service
    self.custom_api.create_namespaced_custom_object(
  File "/home/xxx/anaconda3/envs/faas-scaler/lib/python3.8/site-packages/kubernetes/client/api/custom_objects_api.py", line 225, in create_namespaced_custom_object
    return self.create_namespaced_custom_object_with_http_info(group, version, namespace, plural, body, **kwargs)  # noqa: E501
  File "/home/xxx/anaconda3/envs/faas-scaler/lib/python3.8/site-packages/kubernetes/client/api/custom_objects_api.py", line 344, in create_namespaced_custom_object_with_http_info
    return self.api_client.call_api(
  File "/home/xxx/anaconda3/envs/faas-scaler/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "/home/xxx/anaconda3/envs/faas-scaler/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
  File "/home/xxx/anaconda3/envs/faas-scaler/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 391, in request
    return self.rest_client.POST(url,
  File "/home/xxx/anaconda3/envs/faas-scaler/lib/python3.8/site-packages/kubernetes/client/rest.py", line 275, in POST
    return self.request("POST", url,
  File "/home/xxx/anaconda3/envs/faas-scaler/lib/python3.8/site-packages/kubernetes/client/rest.py", line 234, in request
    raise ApiException(http_resp=r)
kubernetes.client.exceptions.ApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Wed, 18 May 2022 00:54:01 GMT', 'Content-Length': '495'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"admission webhook \"validation.webhook.serving.knative.dev\" denied the request: validation failed: not a DNS 1035 label: [a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name',  or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')]: metadata.name","reason":"BadRequest","code":400}`

**Comment by JosepSampe** [comment]
@FTWH Can you set the Log level to `debug` and post here the logs?

```python
fexec = lithops.FunctionExecutor(log_level='DEBUG')
```

**Comment by JosepSampe** [comment]
@FTWH Regarding the last error, it is caused by a wrong service name that is not allowed by k8s. With DEBUG logs you will see the name of the runtime service that Lithops is trying to deploy to k8s. If you still see this error, please open a different issue since it is different from the original one

**Comment by FTWH** [comment]
> @FTWH Regarding the last error, it is caused by a wrong service name that is not allowed by k8s. With DEBUG logs you will see the name of the runtime service that Lithops is trying to deploy to k8s. If you still see this error, please open a different issue since it is different from the original one

@JosepSampe Thanks a lot for your help! But I have found some new problems. 
1. As shown in the tutorial, the script installs knative @ v0.15 (not the latest version v1.14) as default. Is this version out of the date? What is the version of knative in the recommendation?
2. In the config file, I tried to use the local docker private registry, (docker_server: 192.168.122.11:5000/v2/ ). But it failed to work. And I have not configured "docker_user" yet. What is the reason for that?
Best regards!

**Comment by JosepSampe** [comment]
1. Yes, version 0.15 is outdated. I updated the docs. Now it is much easier to install knative than 1 year ago, so you can simply follow the instructions in the knative website https://knative.dev/docs/install/yaml-install/serving/install-serving-with-yaml instead of using our script
2. Need to check
