### ISSUE TITLE
Cannot run Hello World against Azure

### ISSUE THREAD

**Issue by fplk** [lithops-cloud/lithops#939]
I have been trying to run a simple Hello World Lithops program against Azure:

```python3
import lithops


def hello_world(name):
    return 'Hello {}!'.format(name)

if __name__ == '__main__':


    config = {"lithops": {"backend": "azure_functions", "storage": "azure_storage", "storage_bucket": "apt-falk-meta", "mode": "serverless"}, "azure_storage": {"storage_account_name": "aptregstorageacc", "storage_bucket": "apt-falk-meta", "storage_account_key": "..."}, "azure_functions": {"location": "eastus", "runtime": "regoptsvc", "resource_group": "falk", "functions_version": 3}}

    fexec = lithops.FunctionExecutor(config=config)

    fexec.call_async(hello_world, 'World')
    print(fexec.get_result())
```

When I run it, I hit the following error(s) both on Lithops 2.5.9 and 2.6.0:
```shell
% python validate_lithops.py
2022-06-07 16:58:00,494 [INFO] lithops.config -- Lithops v2.6.0
2022-06-07 16:58:00,762 [INFO] lithops.storage.backends.azure_storage.azure_storage -- Azure Blob client created
2022-06-07 16:58:00,763 [INFO] lithops.serverless.backends.azure_functions.azure_functions -- Azure Functions client created - Location: eastus
2022-06-07 16:58:00,763 [INFO] lithops.invokers -- ExecutorID a20423-0 | JobID A000 - Selected Runtime: regoptsvc - 256MB
2022-06-07 16:58:00,905 [INFO] lithops.invokers -- Runtime regoptsvc with 256MB is not yet deployed
2022-06-07 16:58:00,906 [INFO] lithops.serverless.backends.azure_functions.azure_functions -- Creating new Lithops runtime for Azure Function: regoptsvc
2022-06-07 16:59:28,817 [INFO] lithops.serverless.backends.azure_functions.azure_functions -- Extracting Python modules from: regoptsvc
Traceback (most recent call last):
  File "/Users/fplk/PycharmProjects/predopt/lithops-venv/lib/python3.7/site-packages/lithops/serverless/backends/azure_functions/azure_functions.py", line 328, in _generate_runtime_meta
    payload=payload, return_result=True)
  File "/Users/fplk/PycharmProjects/predopt/lithops-venv/lib/python3.7/site-packages/lithops/serverless/backends/azure_functions/azure_functions.py", line 280, in invoke
    data = json.loads(resp.read().decode("utf-8"))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "validate_lithops.py", line 26, in <module>
    fexec.call_async(hello_world, 'World')
  File "/Users/fplk/PycharmProjects/predopt/lithops-venv/lib/python3.7/site-packages/lithops/executors.py", line 205, in call_async
    runtime_meta = self.invoker.select_runtime(job_id, runtime_memory)
  File "/Users/fplk/PycharmProjects/predopt/lithops-venv/lib/python3.7/site-packages/lithops/invokers.py", line 120, in select_runtime
    runtime_meta = self.compute_handler.deploy_runtime(self.runtime_name, runtime_memory, runtime_timeout)
  File "/Users/fplk/PycharmProjects/predopt/lithops-venv/lib/python3.7/site-packages/lithops/serverless/serverless.py", line 73, in deploy_runtime
    return self.backend.deploy_runtime(runtime_name, memory, timeout=timeout)
  File "/Users/fplk/PycharmProjects/predopt/lithops-venv/lib/python3.7/site-packages/lithops/serverless/backends/azure_functions/azure_functions.py", line 92, in deploy_runtime
    metadata = self._generate_runtime_meta(runtime_name, memory)
  File "/Users/fplk/PycharmProjects/predopt/lithops-venv/lib/python3.7/site-packages/lithops/serverless/backends/azure_functions/azure_functions.py", line 330, in _generate_runtime_meta
    raise Exception("Unable to invoke 'extract-preinstalls' action")
Exception: Unable to invoke 'extract-preinstalls' action
```

On the Azure side I see quite a few resources being created:
- regoptsvc Application Insights and Function App
- EastUSLinuxDynamicPlan App Service plan
- aptregstorageacc Storage account
- aptregopt-lithops-runtime-v37-259-http Application Insights
All under the same resource group.

Interestingly, under Application Insights I see `Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcException`s:
```
Exception while executing function: Functions.lithops_handler Result: Failure
Exception: ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.7 from "/usr/local/bin/python"
  * The NumPy version is: "1.21.6"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'
. Troubleshooting Guide: https://aka.ms/functions-modulenotfound
Stack:   File "/azure-functions-host/workers/python/3.7/LINUX/X64/azure_functions_worker/dispatcher.py", line 309, in _handle__function_load_request
    func_request.metadata.entry_point)
  File "/azure-functions-host/workers/python/3.7/LINUX/X64/azure_functions_worker/utils/wrappers.py", line 42, in call
    raise extend_exception_message(e, message)
  File "/azure-functions-host/workers/python/3.7/LINUX/X64/azure_functions_worker/utils/wrappers.py", line 40, in call
    return func(*args, **kwargs)
  File "/azure-functions-host/workers/python/3.7/LINUX/X64/azure_functions_worker/loader.py", line 85, in load_function
    mod = importlib.import_module(fullmodname)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/site/wwwroot/lithops_handler/__init__.py", line 23, in <module>
    from lithops.worker import function_handler
  File "/home/site/wwwroot/.python_packages/lib/site-packages/lithops/worker/__init__.py", line 1, in <module>
    from .handler import function_handler
  File "/home/site/wwwroot/.python_packages/lib/site-packages/lithops/worker/handler.py", line 38, in <module>
    from lithops.worker.jobrunner import JobRunner
  File "/home/site/wwwroot/.python_packages/lib/site-packages/lithops/worker/jobrunner.py", line 32, in <module>
    import numpy as np
  File "/home/site/wwwroot/.python_packages/lib/site-packages/numpy/__init__.py", line 150, in <module>
    from . import core
  File "/home/site/wwwroot/.python_packages/lib/site-packages/numpy/core/__init__.py", line 48, in <module>
    raise ImportError(msg)
 ```

Finally, I have also conducted an experiment to predeploy Lithops which failed the same way:
I extracted the majority of the Dockerfile from [here](https://github.com/lithops-cloud/lithops/blob/master/lithops/serverless/backends/azure_functions/config.py#L132) and tried to manually build and deploy it with the same results:
```shell
lithops clean -c falk_lithops_azure.config
lithops runtime build -b azure_functions regoptsvc -c falk_lithops_azure.config -f Dockerfile.azure_lithops
lithops runtime deploy -b azure_functions regoptsvc -c falk_lithops_azure.config -d --memory 8192 --timeout 360
```

Finally, this has been exacerbated by the fact that while the other targets have been well documented in the [runtime folder](https://github.com/lithops-cloud/lithops/tree/master/runtime), Azure is still missing from there.

Could you please advice how to proceed and get the hello world to run? Gil Vernik pointed me here.

Thank you very much in advance.

Best wishes,
Falk

**Comment by JosepSampe** [comment]
Hi @fplk, 2 weeks ago I found that they changed something in the Azure side that prevents to use Lithops on there with the latest releases. I already added the fixes the past week, so it should work with the master branch.

Note that currently Azure Functions Lithops backend does not support Docker runtimes. In Azure backend, runtimes are built from a requirements.txt file. Will add the instructions for building a custom runtime to the runtime folder. Also note that Lithops automatically builds and deploys a default runtime the first time you run a function, so for running the `hello world` app you don't need to either build or deploy any runtime.

**Comment by fplk** [comment]
Well, I ultimately went against master as mentioned in the other issue, but am facing the same or a very similar issue:
```
2022-06-08 12:51:33,767 [INFO] azure_functions.py:313 -- Extracting metadata from: lithops-default-runtime-v37
Traceback (most recent call last):
  File "/Users/fplk/PycharmProjects/predopt/lithops-venv/lib/python3.7/site-packages/lithops/serverless/backends/azure_functions/azure_functions.py", line 318, in _generate_runtime_meta
    payload=payload, return_result=True)
  File "/Users/fplk/PycharmProjects/predopt/lithops-venv/lib/python3.7/site-packages/lithops/serverless/backends/azure_functions/azure_functions.py", line 271, in invoke
    data = json.loads(resp.read().decode("utf-8"))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 15, in <module>
    fexec.call_async(my_function, 3)
  File "/Users/fplk/PycharmProjects/predopt/lithops-venv/lib/python3.7/site-packages/lithops/executors.py", line 205, in call_async
    runtime_meta = self.invoker.select_runtime(job_id, runtime_memory)
  File "/Users/fplk/PycharmProjects/predopt/lithops-venv/lib/python3.7/site-packages/lithops/invokers.py", line 117, in select_runtime
    runtime_meta = self.compute_handler.deploy_runtime(self.runtime_name, runtime_memory, runtime_timeout)
  File "/Users/fplk/PycharmProjects/predopt/lithops-venv/lib/python3.7/site-packages/lithops/serverless/serverless.py", line 73, in deploy_runtime
    return self.backend.deploy_runtime(runtime_name, memory, timeout=timeout)
  File "/Users/fplk/PycharmProjects/predopt/lithops-venv/lib/python3.7/site-packages/lithops/serverless/backends/azure_functions/azure_functions.py", line 90, in deploy_runtime
    metadata = self._generate_runtime_meta(runtime_name, memory)
  File "/Users/fplk/PycharmProjects/predopt/lithops-venv/lib/python3.7/site-packages/lithops/serverless/backends/azure_functions/azure_functions.py", line 320, in _generate_runtime_meta
    raise Exception(f"Unable to extract metadata: {e}")
Exception: Unable to extract metadata: Expecting value: line 1 column 1 (char 0)
(lithops-venv) fplk@Falks-MacBook-Pro lithopsDebugging % lithops --version
lithops, version 2.6.1.dev0
```
Please also note that this seems at odds with your clarification that Azure does not support Docker - why did it reach azure_functions.py, line 318 then? It seems it should have never gotten there.
```
        try:
            runtime_meta = self.invoke(docker_image_name, memory=memory,
                                       payload=payload, return_result=True)
        except Exception as e:
            raise Exception(f"Unable to extract metadata: {e}")
```

Please also note that I changed the runtime name multiple times during debugging, so I tried "default" besides "default2" and others, since I assume the `"runtime": "regoptsvc"` above could be wrong. Without runtime docs it's difficult to tell - any advice might be helpful. Thanks in advance.

**Comment by JosepSampe** [comment]
can you run `lithops clean -c falk_lithops_azure.config` and then try again with DEBUG logs?

**Comment by fplk** [comment]
Sure:
```
2022-06-08 13:28:28,903 [DEBUG] azure_functions.py:204 -- Publishing function: aptregstorageacc-lithops-default-runtime-v37-2-6-1-dev0-http
Can't find app with name "aptregstorageacc-lithops-default-runtime-v37-2-6-1-dev0-http"

Getting site publishing info...
Skipping build event for functions project (--no-build).
Uploading package...
Uploading 40 MB [------------------------------------------------------------Upload completed successfully.
Deployment completed successfully.
Syncing triggers...
Functions in aptregstorageacc-lithops-default-runtime-v37-2-6-1-dev0-http:
    lithops_handler - [httpTrigger]
        Invoke url: https://aptregstorageacc-lithops-default-runtime-v37-2-6-1-dev0-http.azurewebsites.net/api/lithops_handler

2022-06-08 13:29:13,349 [INFO] azure_functions.py:313 -- Extracting metadata from: lithops-default-runtime-v37

---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
~/PycharmProjects/predopt/lithops-venv/lib/python3.7/site-packages/lithops/serverless/backends/azure_functions/azure_functions.py in _generate_runtime_meta(self, docker_image_name, memory)
    317             runtime_meta = self.invoke(docker_image_name, memory=memory,
--> 318                                        payload=payload, return_result=True)
    319         except Exception as e:

~/PycharmProjects/predopt/lithops-venv/lib/python3.7/site-packages/lithops/serverless/backends/azure_functions/azure_functions.py in invoke(self, docker_image_name, memory, payload, return_result)
    270                 resp = conn.getresponse()
--> 271                 data = json.loads(resp.read().decode("utf-8"))
    272                 conn.close()

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    347             parse_constant is None and object_pairs_hook is None and not kw):
--> 348         return _default_decoder.decode(s)
    349     if cls is None:

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py in decode(self, s, _w)
    336         """
--> 337         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    338         end = _w(s, end).end()

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py in raw_decode(self, s, idx)
    354         except StopIteration as err:
--> 355             raise JSONDecodeError("Expecting value", s, err.value) from None
    356         return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
/var/folders/qp/wxndn8ds2gz8ysz5mxqx86880000gn/T/ipykernel_4549/2400594072.py in <module>
----> 1 fexec.call_async(my_function, 3)

~/PycharmProjects/predopt/lithops-venv/lib/python3.7/site-packages/lithops/executors.py in call_async(self, func, data, extra_env, runtime_memory, timeout, include_modules, exclude_modules)
    203         self.last_call = 'call_async'
    204 
--> 205         runtime_meta = self.invoker.select_runtime(job_id, runtime_memory)
    206 
    207         job = create_map_job(config=self.config,

~/PycharmProjects/predopt/lithops-venv/lib/python3.7/site-packages/lithops/invokers.py in select_runtime(self, job_id, runtime_memory)
    115             msg = msg+' with {}MB'.format(runtime_memory) if runtime_memory else msg
    116             logger.info(msg+' is not yet deployed')
--> 117             runtime_meta = self.compute_handler.deploy_runtime(self.runtime_name, runtime_memory, runtime_timeout)
    118             runtime_meta['runtime_timeout'] = runtime_timeout
    119             self.internal_storage.put_runtime_meta(runtime_key, runtime_meta)

~/PycharmProjects/predopt/lithops-venv/lib/python3.7/site-packages/lithops/serverless/serverless.py in deploy_runtime(self, runtime_name, memory, timeout)
     71         return: the name of the runtime
     72         """
---> 73         return self.backend.deploy_runtime(runtime_name, memory, timeout=timeout)
     74 
     75     def delete_runtime(self, runtime_name, memory):

~/PycharmProjects/predopt/lithops-venv/lib/python3.7/site-packages/lithops/serverless/backends/azure_functions/azure_functions.py in deploy_runtime(self, runtime_name, memory, timeout)
     88         logger.info(f"Deploying runtime: {runtime_name} - Memory: {memory} Timeout: {timeout}")
     89         self._create_function(runtime_name, memory, timeout)
---> 90         metadata = self._generate_runtime_meta(runtime_name, memory)
     91 
     92         return metadata

~/PycharmProjects/predopt/lithops-venv/lib/python3.7/site-packages/lithops/serverless/backends/azure_functions/azure_functions.py in _generate_runtime_meta(self, docker_image_name, memory)
    318                                        payload=payload, return_result=True)
    319         except Exception as e:
--> 320             raise Exception(f"Unable to extract metadata: {e}")
    321 
    322         if not runtime_meta or 'preinstalls' not in runtime_meta:

Exception: Unable to extract metadata: Expecting value: line 1 column 1 (char 0)
```

Side question: Should I care about this?
```
WARNING: Your Linux function app 'aptregstorageacc-lithops-default-runtime-v37-2-6-1-dev0-http', that uses a consumption plan has been successfully created but is not active until content is published using Azure Portal or the Functions Core Tools.
```

**Comment by JosepSampe** [comment]
I've been trying to replicate the issue but for me it always works ok. [I just added a change](https://github.com/lithops-cloud/lithops/pull/941) that will show the actual error that is produced when it tries to extract the metadata from the runtime. Can you update your installation from the master branch and try again?

**Comment by theathibm** [comment]
@JosepSampe, Do you have a working example of a hello world type of application using lithops and azure?

Do you use lithops runtime build and lithops runtime deploy to do it?  If so can you send the dockerfile you use.

Do you just use a lithops config only and bypass the lithops runtime build and lithops runtime deploy?

We really need to see how to run on Azure, otherwise we might have to punt on lithops altogether.

**Comment by JosepSampe** [comment]
Hi @theathibm, I'm using the basic "hello world" function we have, with the default runtime that is automatically built. You can submit it with `lithops test -b azure_functions -s azure_storage -d`

You don't need to run "create" and "deploy", everything is automatically done by lithops.

Note that currently Azure backend for Lithops does not support Docker containers. This morning I added the instructions in the runtime folder on how to create a custom runtime based on a requeriments.txt file if you need a custom runtime

**Comment by theathibm** [comment]
@JosepSampe , thanks.    We will need to build customized runtimes for our various custom python modules which all need to be cythonized.

Can you send lithops configuration file that has everything needed for a successful azure deployment?

**Comment by JosepSampe** [comment]
There is no special configuration. The configuration that @fplk provided on the top of this thread is good. In fact the runtime is correctly built and deployed. You should check the azure portal and see in the function logs why it is failing.

**Comment by theathibm** [comment]
Also, would like more clarity on this error snippet from the above:

Please note and check the following:

  * The Python version is: Python3.7 from "/usr/local/bin/python"
  * The NumPy version is: "1.21.6"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'

**Comment by JosepSampe** [comment]
This could happen if you have diferent versions of numpy in the client and in the runtime

**Comment by fplk** [comment]
Launching from Linux (or rather a Linux container from macOS) resolved the issue. Thank you.
