### ISSUE TITLE
Cannot run Hello World against KNative

### ISSUE THREAD

**Issue by fplk** [lithops-cloud/lithops#940]
Since Azure didn't work, I now tried KNative. I setup a MinIO instance (and validated it works with Python code I wrote against it), then wrote the following configuration:

```yaml
lithops:
    backend: knative
    storage: minio

knative:
    docker_server: docker.io
    docker_user: ...
    docker_password: ...


minio:
    storage_bucket: falk
    endpoint: http://9.106.227.153:9000
    access_key_id: ...
    secret_access_key: ...
```

And then I deployed KNative with Istio against Minikube to try it:
```shell
minikube start
kubectl config set-context minikube
kubectl config get-contexts
```

```shell
kubectl apply -f https://github.com/knative/serving/releases/download/knative-v1.5.0/serving-crds.yaml
kubectl apply -f https://github.com/knative/serving/releases/download/knative-v1.5.0/serving-core.yaml
```

Istio
```shell
kubectl apply -l knative.dev/crd-install=true -f https://github.com/knative/net-istio/releases/download/knative-v1.5.0/istio.yaml
kubectl apply -f https://github.com/knative/net-istio/releases/download/knative-v1.5.0/istio.yaml

kubectl apply -f https://github.com/knative/net-istio/releases/download/knative-v1.5.0/net-istio.yaml

kubectl --namespace istio-system get service istio-ingressgateway
```

```shell
kubectl get pods -n knative-serving

lithops runtime deploy default -b knative -c lithops_knative.config
```

The error I hit is:
```
% lithops runtime deploy default -b knative -c lithops_knative.config
2022-06-07 20:39:50,452 [INFO] lithops.config -- Lithops v2.6.0
2022-06-07 20:39:50,452 [DEBUG] lithops.config -- Loading Serverless backend module: knative
2022-06-07 20:39:50,717 [DEBUG] lithops.config -- Loading Storage backend module: minio
2022-06-07 20:39:50,769 [INFO] lithops.scripts.cli -- Creating new lithops runtime: default
2022-06-07 20:39:50,769 [DEBUG] lithops.storage.backends.minio.minio -- Creating MinIO client
2022-06-07 20:39:50,769 [DEBUG] lithops.storage.backends.minio.minio -- Setting MinIO endpoint to http://9.106.227.153:9000
2022-06-07 20:39:50,835 [INFO] lithops.storage.backends.minio.minio -- MinIO client created - Endpoint: http://9.106.227.153:9000
2022-06-07 20:39:50,883 [DEBUG] lithops.serverless.backends.knative.knative -- Set namespace to default
2022-06-07 20:39:50,883 [DEBUG] lithops.serverless.backends.knative.knative -- Set cluster to minikube
2022-06-07 20:39:50,912 [DEBUG] lithops.serverless.backends.knative.knative -- Loaded service host suffix: None
2022-06-07 20:39:50,912 [INFO] lithops.serverless.backends.knative.knative -- Knative client created - Istio Endpoint: http://192.168.49.2:31376
Traceback (most recent call last):
  File "/Users/fplk/PycharmProjects/predopt/lithops-venv/bin/lithops", line 8, in <module>
    sys.exit(lithops_cli())
  File "/Users/fplk/PycharmProjects/predopt/lithops-venv/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/fplk/PycharmProjects/predopt/lithops-venv/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/fplk/PycharmProjects/predopt/lithops-venv/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/fplk/PycharmProjects/predopt/lithops-venv/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/fplk/PycharmProjects/predopt/lithops-venv/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/fplk/PycharmProjects/predopt/lithops-venv/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/fplk/PycharmProjects/predopt/lithops-venv/lib/python3.7/site-packages/lithops/scripts/cli.py", line 476, in deploy
    mem = memory if memory else compute_config['runtime_memory']
KeyError: 'runtime_memory'
```

Could you give me any pointers?

KNative seems fine:
```
% kubectl get pods -n knative-serving
NAME                                    READY   STATUS    RESTARTS   AGE
activator-67688f67c6-tcbm2              1/1     Running   0          8m40s
autoscaler-58f7dfdb67-dkgtd             1/1     Running   0          8m40s
controller-6ddd5b667d-fwwn6             1/1     Running   0          8m40s
domain-mapping-9657f967f-x27td          1/1     Running   0          8m40s
domainmapping-webhook-f5bfc7479-d4kkl   1/1     Running   0          8m40s
net-istio-controller-998b46c7f-wtm94    1/1     Running   0          6m39s
net-istio-webhook-687bb6b995-xt2b6      1/1     Running   0          6m39s
webhook-5c4bff9565-gj6wq                1/1     Running   0          8m40s
```

The only thing remotely out of order I can find is that my ingress gateway has no external IP (as expected):
```
% kubectl --namespace istio-system get service istio-ingressgateway
NAME                   TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                                      AGE
istio-ingressgateway   LoadBalancer   10.100.226.56   <pending>     15021:32197/TCP,80:31376/TCP,443:30887/TCP   7m48s
```

Could this be that my cluster cannot connect to my machine with MinIO or what does the
> KeyError: 'runtime_memory'

mean?

Thank you in advance.

PS:
I have also placed `runtime_memory: 512` in my configuration file - I even copied it everywhere in the configuration in a final attempt, i.e., knative, minio, lithops, root level - it still complains `runtime_memory` is not defined.

PPS:
OK, got it working against K8s at least. However, NOT against KNative thus far. I now understand that I need to use Lithops from master (`python -m pip install git+https://github.com/lithops-cloud/lithops.git@master`) to have a chance with KNative and that I need to set the memory and timeout from the CLI, but while I have been able to eliminate errors with this, it now timeouts:
```
% lithops runtime deploy default2 -b knative -c lithops_knative.config --memory 512 --timeout 20
2022-06-07 22:37:43,227 [INFO] config.py:131 -- Lithops v2.6.1.dev0
2022-06-07 22:37:43,227 [DEBUG] config.py:183 -- Loading Serverless backend module: knative
2022-06-07 22:37:43,512 [DEBUG] config.py:248 -- Loading Storage backend module: minio
2022-06-07 22:37:43,566 [DEBUG] minio.py:37 -- Creating MinIO client
2022-06-07 22:37:43,566 [DEBUG] minio.py:42 -- Setting MinIO endpoint to http://9.106.227.153:9000
2022-06-07 22:37:43,674 [INFO] minio.py:60 -- MinIO client created - Endpoint: http://9.106.227.153:9000
2022-06-07 22:37:43,738 [DEBUG] knative.py:75 -- Set namespace to default
2022-06-07 22:37:43,738 [DEBUG] knative.py:76 -- Set cluster to minikube
2022-06-07 22:37:43,764 [DEBUG] knative.py:106 -- Istio endpoint set to http://192.168.49.2:31376
2022-06-07 22:37:43,764 [INFO] knative.py:122 -- Knative client created - Cluster: minikube
2022-06-07 22:37:43,764 [INFO] knative.py:538 -- Deploying runtime: default2 - Memory: 512 Timeout: 20
2022-06-07 22:37:43,764 [DEBUG] knative.py:385 -- Creating container registry secret
2022-06-07 22:37:43,782 [DEBUG] knative.py:428 -- Creating Lithops runtime service in Knative
2022-06-07 22:37:43,787 [DEBUG] knative.py:435 -- Service name: default2--512mb
2022-06-07 22:37:43,787 [DEBUG] knative.py:436 -- Namespace: default
2022-06-07 22:42:43,511 [DEBUG] knative.py:493 -- Runtime Service created - URL: http://default2--512mb.default.example.com
2022-06-07 22:42:43,514 [INFO] knative.py:508 -- Extracting metadata from: default2
2022-06-07 22:42:43,514 [DEBUG] knative.py:671 -- Invoking function
Traceback (most recent call last):
  File "/Users/fplk/PycharmProjects/predopt/lithops-venv/lib/python3.7/site-packages/lithops/serverless/backends/knative/knative.py", line 514, in _generate_runtime_meta
    runtime_meta = self.invoke(docker_image_name, memory, payload, return_result=True)
  File "/Users/fplk/PycharmProjects/predopt/lithops-venv/lib/python3.7/site-packages/lithops/serverless/backends/knative/knative.py", line 681, in invoke
    raise e
  File "/Users/fplk/PycharmProjects/predopt/lithops-venv/lib/python3.7/site-packages/lithops/serverless/backends/knative/knative.py", line 673, in invoke
    conn.request("POST", route, body=json.dumps(payload, default=str), headers=headers)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1277, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1323, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1272, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1032, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 972, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 944, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/fplk/PycharmProjects/predopt/lithops-venv/bin/lithops", line 11, in <module>
    load_entry_point('lithops==2.6.1.dev0', 'console_scripts', 'lithops')()
  File "/Users/fplk/PycharmProjects/predopt/lithops-venv/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/fplk/PycharmProjects/predopt/lithops-venv/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/fplk/PycharmProjects/predopt/lithops-venv/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/fplk/PycharmProjects/predopt/lithops-venv/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/fplk/PycharmProjects/predopt/lithops-venv/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/fplk/PycharmProjects/predopt/lithops-venv/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/fplk/PycharmProjects/predopt/lithops-venv/lib/python3.7/site-packages/lithops/scripts/cli.py", line 490, in deploy
    runtime_meta = compute_handler.deploy_runtime(runtime_name, runtime_memory, runtime_timeout)
  File "/Users/fplk/PycharmProjects/predopt/lithops-venv/lib/python3.7/site-packages/lithops/serverless/serverless.py", line 73, in deploy_runtime
    return self.backend.deploy_runtime(runtime_name, memory, timeout=timeout)
  File "/Users/fplk/PycharmProjects/predopt/lithops-venv/lib/python3.7/site-packages/lithops/serverless/backends/knative/knative.py", line 541, in deploy_runtime
    runtime_meta = self._generate_runtime_meta(docker_image_name, memory)
  File "/Users/fplk/PycharmProjects/predopt/lithops-venv/lib/python3.7/site-packages/lithops/serverless/backends/knative/knative.py", line 516, in _generate_runtime_meta
    raise Exception(f"Unable to extract metadata from the runtime: {e}")
Exception: Unable to extract metadata from the runtime: [Errno 60] Operation timed out
```

PPPS:
One thing I don't get, either, is that when I just blindly run a hello world program via Python with that image, it "works":
```
% python helloworld.py
2022-06-07 23:37:52,968 [INFO] config.py:131 -- Lithops v2.6.1.dev0
2022-06-07 23:37:52,970 [INFO] localhost.py:40 -- Localhost storage client created
2022-06-07 23:37:52,970 [INFO] localhost.py:57 -- Localhost compute client created
2022-06-07 23:37:52,970 [INFO] invokers.py:108 -- ExecutorID 094445-0 | JobID A000 - Selected Runtime: fplk/lithopsknative:v2
2022-06-07 23:37:52,971 [INFO] invokers.py:116 -- Runtime fplk/lithopsknative:v2 is not yet deployed
2022-06-07 23:37:52,971 [INFO] localhost.py:119 -- Deploying runtime: fplk/lithopsknative:v2
2022-06-07 23:37:54,724 [INFO] invokers.py:175 -- ExecutorID 094445-0 | JobID A000 - Starting function invocation: hello_world() - Total: 1 activations
2022-06-07 23:37:54,725 [INFO] invokers.py:209 -- ExecutorID 094445-0 | JobID A000 - View execution logs at /private/var/folders/qp/wxndn8ds2gz8ysz5mxqx86880000gn/T/lithops/logs/094445-0-A000.log
2022-06-07 23:37:54,725 [INFO] wait.py:95 -- ExecutorID 094445-0 - Getting results from 1 function activations

  100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1

2022-06-07 23:37:56,779 [INFO] executors.py:564 -- ExecutorID 094445-0 - Cleaning temporary data
Hello World!
```
for this program which I ran via `python helloworld.py`:
```python3
import lithops


def hello_world(name):
    return 'Hello {}!'.format(name)

if __name__ == '__main__':

    fexec = lithops.FunctionExecutor(runtime='fplk/lithopsknative:v2')

    fexec.call_async(hello_world, 'World')
    print(fexec.get_result())
```

But that didn't take my configuration - neither for KNative nor for MinIO, so I'm not exactly sure what this does under the covers.

**Comment by JosepSampe** [comment]
@fplk As you found master branch contains fixes necessary for this. Note that this is not valid: `lithops runtime deploy default2 -b knative -c lithops_knative.config` you must use the word `default` and not `default2` for deploying the default runtime

**Comment by theathibm** [comment]
@JosepSampe, We will also need working examples of knative. Please send anything you can in regards to working examples for knative and azure.    You can remove all your credential information from the examples and use our credentials instead.  Thanks.

**Comment by JosepSampe** [comment]
@theathibm Any example in this repo should work in knative, since at application level everything is generic. Probably the error we are facing here is about Istio configuration. Need to check what configuration is missing for Istio.

In any case, I recently added support for `Kourier` networking layer, which does not need any extra configuration. Just run the steps [from here](https://knative.dev/docs/install/yaml-install/serving/install-serving-with-yaml/#install-a-networking-layer) to install it.

For executing a hello world function you only need to execute this command (this will automatically build and deploy the default runtime):
```
$ lithops test -b knative -c lithops_knative.config -d
```

Note that Lithops tries to automatically get the Public IP and the port from the kourier service (which is the entry point for knative). In the Lithops logs of the previous command you should see something like this:
```
2022-06-11 16:42:17,115 [DEBUG] knative.py:114 -- Ingress endpoint set to http://165.23.36.32:31179
```

In case the endpoint automatically obtained by Lithops is wrong, You must find a Public IP of your cluster, and provide the endpoint in the config:
```
knative:
    ingress_endpoint: http://PUBLIC_IP:PORT
```

You can check the port using the next command: (You must choose the port on which port 80 is mapped, i.e. in my case 31179)
```
$ kubectl --namespace kourier-system get service kourier
NAME      TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)                      AGE
kourier   LoadBalancer   172.21.45.15   <pending>     80:31179/TCP,443:31258/TCP   13h
```

**Comment by fplk** [comment]
Still doesn't seem to work. I deployed Kourier and tried MinIO, IBM COS and Azure storage backends without success. The code still times out with the same error reported above:
```
2022-06-13 02:20:07,263 [DEBUG] knative.py:679 -- Invoking function
Traceback (most recent call last):
  File "/Users/fplk/PycharmProjects/predopt/lithops-venv/lib/python3.7/site-packages/lithops/serverless/backends/knative/knative.py", line 522, in _generate_runtime_meta
    runtime_meta = self.invoke(docker_image_name, memory, payload, return_result=True)
  File "/Users/fplk/PycharmProjects/predopt/lithops-venv/lib/python3.7/site-packages/lithops/serverless/backends/knative/knative.py", line 689, in invoke
    raise e
  File "/Users/fplk/PycharmProjects/predopt/lithops-venv/lib/python3.7/site-packages/lithops/serverless/backends/knative/knative.py", line 681, in invoke
    conn.request("POST", route, body=json.dumps(payload, default=str), headers=headers)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1277, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1323, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1272, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1032, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 972, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 944, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/fplk/PycharmProjects/predopt/lithops-venv/bin/lithops", line 11, in <module>
    load_entry_point('lithops==2.6.1.dev0', 'console_scripts', 'lithops')()
  File "/Users/fplk/PycharmProjects/predopt/lithops-venv/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/fplk/PycharmProjects/predopt/lithops-venv/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/fplk/PycharmProjects/predopt/lithops-venv/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/fplk/PycharmProjects/predopt/lithops-venv/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/fplk/PycharmProjects/predopt/lithops-venv/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/fplk/PycharmProjects/predopt/lithops-venv/lib/python3.7/site-packages/lithops/scripts/cli.py", line 173, in test_function
    fexec.call_async(hello, username)
  File "/Users/fplk/PycharmProjects/predopt/lithops-venv/lib/python3.7/site-packages/lithops/executors.py", line 209, in call_async
    runtime_meta = self.invoker.select_runtime(job_id, runtime_memory)
  File "/Users/fplk/PycharmProjects/predopt/lithops-venv/lib/python3.7/site-packages/lithops/invokers.py", line 117, in select_runtime
    runtime_meta = self.compute_handler.deploy_runtime(self.runtime_name, runtime_memory, runtime_timeout)
  File "/Users/fplk/PycharmProjects/predopt/lithops-venv/lib/python3.7/site-packages/lithops/serverless/serverless.py", line 73, in deploy_runtime
    return self.backend.deploy_runtime(runtime_name, memory, timeout=timeout)
  File "/Users/fplk/PycharmProjects/predopt/lithops-venv/lib/python3.7/site-packages/lithops/serverless/backends/knative/knative.py", line 549, in deploy_runtime
    runtime_meta = self._generate_runtime_meta(docker_image_name, memory)
  File "/Users/fplk/PycharmProjects/predopt/lithops-venv/lib/python3.7/site-packages/lithops/serverless/backends/knative/knative.py", line 524, in _generate_runtime_meta
    raise Exception(f"Unable to extract metadata from the runtime: {e}")
Exception: Unable to extract metadata from the runtime: [Errno 60] Operation timed out
```

The ingress_endpoint is indeed wrong, but setting it as you described didn't help. If I manually run my own code against the storage backends, I have no problem to access them. Additional instructions would be appreciated.
